Repository treehouses/remote, pull requests merged in 2020-07, with the labels that each got.

#996 settings: dark mode (fixes #851)
  app/src/main/java/io/treehouses/remote/Fragments/SettingsFragment.kt
  app/src/main/java/io/treehouses/remote/pojo/ServicesData.kt
  app/src/main/res/layout/custom_pref.xml
  app/src/main/res/layout/custom_pref_category.xml
  app/src/main/res/values-night/color.xml
  app/src/main/res/values/color.xml
  app/src/main/res/xml/app_preferences.xml
Labels: :eye: please review, priority

#1001 home, network and services: background with xml
  app/src/main/res/drawable/bluetooth_btn.xml
  app/src/main/res/drawable/profiles_back.xml
  app/src/main/res/drawable/profiles_background.png
  app/src/main/res/drawable/test_connection.png
  app/src/main/res/layout/activity_home_fragment.xml
  app/src/main/res/layout/activity_services_tab_fragment.xml
  app/src/main/res/layout/new_network.xml
Labels: :eye: please review, enhancement, priority

#956 terminal: tutorial and refactor (fixes #934)
  app/src/main/java/io/treehouses/remote/Tutorials.kt
  app/src/main/res/values-night/color.xml
  app/src/main/res/values/color.xml
Labels: :eye: please review, priority

#959 settings: add led patterns (fixes #899)
  app/src/main/java/io/treehouses/remote/bases/BaseHomeFragment.kt
  app/src/main/res/drawable/carnival_anim_green.xml
  app/src/main/res/drawable/carnival_anim_red.xml
  app/src/main/res/drawable/christmas_anim_green.xml
  app/src/main/res/drawable/christmas_anim_red.xml
  app/src/main/res/drawable/diwali_anim_green.xml
  app/src/main/res/drawable/diwali_anim_red.xml
  app/src/main/res/drawable/easter_anim_green.xml
  app/src/main/res/drawable/easter_anim_red.xml
  app/src/main/res/drawable/eid_anim_green.xml
  app/src/main/res/drawable/eid_anim_red.xml
  app/src/main/res/drawable/kecak_anim_green.xml
  app/src/main/res/drawable/kecak_anim_red.xml
  app/src/main/res/drawable/lantern_anim_green.xml
  app/src/main/res/drawable/lantern_anim_red.xml
  app/src/main/res/drawable/lunarnewyear_anim_green.xml
  app/src/main/res/drawable/lunarnewyear_anim_red.xml
  app/src/main/res/drawable/onam_anim_green.xml
  app/src/main/res/drawable/onam_anim_red.xml
  app/src/main/res/drawable/stpatricks_anim_green.xml
  app/src/main/res/drawable/valentine_anim_green.xml
  app/src/main/res/drawable/valentine_anim_red.xml
  app/src/main/res/values-night/strings.xml
  app/src/main/res/values/strings.xml
Labels: :eye: please review, priority

#994 system: add blocker (fixes #1035)
  app/src/main/java/io/treehouses/remote/adapter/ViewHolderBlocker.kt
Labels: :eye: please review, priority

#868 home: menu grayed out when not connected (fixes #830)
  app/src/main/java/io/treehouses/remote/Fragments/HomeFragment.kt
  app/src/main/java/io/treehouses/remote/InitialActivity.kt
  app/src/main/res/color/navigation_menu_text.xml
  app/src/main/res/drawable-anydpi/navigation_menu_bg.xml
  app/src/main/res/layout/activity_initial2.xml
  app/src/main/res/menu/activity_initial2_drawer.xml
  app/src/main/res/values-night/color.xml
  app/src/main/res/values/color.xml
Labels: :eye: please review, priority

#873 convert ServiceCardAdapter to kotlin
  app/src/main/java/io/treehouses/remote/adapter/ServiceCardAdapter.java
  app/src/main/java/io/treehouses/remote/adapter/ServiceCardAdapter.kt
Labels: :eye: please review

#1004 convert ViewHolderTether to kotlin
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/treehouses/remote/Fragments/SystemFragment.kt
  app/src/main/java/io/treehouses/remote/adapter/NetworkListAdapter.kt
  app/src/main/java/io/treehouses/remote/adapter/ViewHolderTether.java
  app/src/main/java/io/treehouses/remote/adapter/ViewHolderTether.kt
  app/src/main/res/layout/configure_tethering.xml
Labels: :eye: please review

#962 tunnel: delete TorBottomSheet (fixes #1025)
  app/src/main/java/io/treehouses/remote/Fragments/DialogFragments/BottomSheetDialogs/TorBottomSheet.java
Labels: :eye: please review

#1036 terminal: shrink text (fixes #1008)
  app/src/main/res/layout/activity_terminal_fragment.xml
Labels: :eye: please review, dogi

#1019 setting: red headings in dark mode (fixes #1018)
  app/src/main/res/layout/custom_pref_category.xml
Labels: :eye: please review, dogi, enhancement

#1007 refactor due to travis warnings (fixes #1006)
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/treehouses/remote/Fragments/AboutFragment.kt
  app/src/main/java/io/treehouses/remote/Fragments/DialogFragments/AddCommandDialogFragment.kt
  app/src/main/java/io/treehouses/remote/Fragments/DialogFragments/BottomSheetDialogs/BridgeBottomSheet.kt
  app/src/main/java/io/treehouses/remote/Fragments/DialogFragments/ChPasswordDialogFragment.kt
  app/src/main/java/io/treehouses/remote/Fragments/DialogFragments/RPIDialogFragment.kt
  app/src/main/java/io/treehouses/remote/Fragments/DialogFragments/WifiDialogFragment.kt
  app/src/main/java/io/treehouses/remote/Fragments/HomeFragment.kt
  app/src/main/java/io/treehouses/remote/Fragments/ServiceCardFragment.kt
  app/src/main/java/io/treehouses/remote/Fragments/ServicesDetailsFragment.kt
  app/src/main/java/io/treehouses/remote/Fragments/ServicesFragment.kt
  app/src/main/java/io/treehouses/remote/Fragments/ServicesTabFragment.kt
  app/src/main/java/io/treehouses/remote/Fragments/SettingsFragment.kt
  app/src/main/java/io/treehouses/remote/Fragments/TerminalFragment.kt
  app/src/main/java/io/treehouses/remote/Fragments/TextBoxValidation.kt
  app/src/main/java/io/treehouses/remote/Fragments/TorTabFragment.kt
  app/src/main/java/io/treehouses/remote/InitialActivity.kt
  app/src/main/java/io/treehouses/remote/SplashScreenActivity.kt
  app/src/main/java/io/treehouses/remote/adapter/CommandListAdapter.kt
  app/src/main/java/io/treehouses/remote/adapter/NetworkListAdapter.kt
  app/src/main/java/io/treehouses/remote/adapter/ServicesListAdapter.kt
  app/src/main/java/io/treehouses/remote/adapter/ViewHolderCamera.kt
  app/src/main/java/io/treehouses/remote/adapter/ViewHolderSSHKey.kt
  app/src/main/java/io/treehouses/remote/adapter/ViewHolderVnc.kt
  app/src/main/java/io/treehouses/remote/adapter/ViewHolderWifiCountry.kt
  app/src/main/java/io/treehouses/remote/bases/BaseServicesFragment.kt
  app/src/main/java/io/treehouses/remote/bases/BaseTerminalFragment.kt
  app/src/main/java/io/treehouses/remote/bases/PermissionActivity.kt
  app/src/main/java/io/treehouses/remote/pojo/ServiceInfo.kt
  app/src/main/java/io/treehouses/remote/utils/LogUtils.kt
  app/src/main/java/io/treehouses/remote/utils/Utils.kt
Labels: :eye: please review

#995 settings: reactivate tutorials (fixes #977)
  app/src/main/java/io/treehouses/remote/Fragments/SettingsFragment.kt
  app/src/main/res/xml/app_preferences.xml
Labels: :eye: please review, priority

#1044 refactor GPSService.kt (fixes #1034)
  app/src/main/java/io/treehouses/remote/utils/GPSService.kt
Labels: :eye: please review, refactor

#1047 home: dark mode for network profiles list (fixes #1027)
  app/src/main/java/io/treehouses/remote/adapter/ProfilesListAdapter.java
  app/src/main/res/drawable/expandlist_foreground.xml
  app/src/main/res/layout/list_group.xml
  app/src/main/res/layout/row_profile.xml
  app/src/main/res/values-night/color.xml
  app/src/main/res/values/color.xml
Labels: :eye: please review, enhancement

#1017 services: added call to start services overview tutorial (fixes #1016)
  app/src/main/java/io/treehouses/remote/Fragments/ServicesTabFragment.kt
  app/src/main/java/io/treehouses/remote/Tutorials.kt
Labels: :eye: please review, priority

#1037 convert NetworkListAdapter to kotlin (fixes #1032)
  app/src/main/java/io/treehouses/remote/Fragments/SystemFragment.kt
  app/src/main/java/io/treehouses/remote/pojo/NetworkListItem.java
  app/src/main/java/io/treehouses/remote/pojo/NetworkListItem.kt
Labels: :eye: please review, priority

#1059 services: normed icon size and background (fixes #1058)
  app/src/main/res/layout/service_card.xml
Labels: :eye: please review

#1003 update build.gradle (fixes #1005)
  app/build.gradle
Labels: :eye: please review, priority

#1014 tutorials: refactor (fixes #1009)
  app/src/main/java/io/treehouses/remote/Tutorials.kt
Labels: :eye: please review

#1021 tunnel: number keyboard (fixes #1011)
  app/src/main/res/layout/dialog_tor_ports.xml
Labels: :eye: please review

#1043 home: get started (fixes #1039)
  app/src/main/java/io/treehouses/remote/Fragments/HomeFragment.kt
Labels: :eye: please review

#1023 tunnel: tor constraints (fixes #1010)
  app/src/main/res/layout/activity_tor_fragment.xml
Labels: :eye: please review

#1052 tunnel: remove empty tor port (fixes #1024)
  app/src/main/java/io/treehouses/remote/Fragments/TorTabFragment.kt
Labels: :eye: please review

#1056 terminal: white text for dark mode (fixes #1048)
  app/src/main/java/io/treehouses/remote/bases/BaseTerminalFragment.kt
  app/src/main/res/values-night/color.xml
  app/src/main/res/values/color.xml
Labels: :eye: please review

#1061 services: switch to settings without oops (fixes #1060)
  app/src/main/java/io/treehouses/remote/Fragments/ServicesFragment.kt
Labels: :eye: please review, bug

#1042 status: icon fix (fixes #1040)
  app/src/main/java/io/treehouses/remote/InitialActivity.kt
Labels: :eye: please review, bug, dogi

#1068 settings: dialog popups dark mode (fixes #1029)
  app/src/main/res/values-night/styles.xml
  app/src/main/res/values/styles.xml
Labels: :eye: please review, enhancement

#1054 update .gitlab-ci.yml (fixes #992)
  .gitlab-ci.yml
Labels: :eye: please review

#1064 services: loading background dark compatible (fixes #1065)
  app/src/main/res/layout/activity_services_fragment.xml
Labels: :eye: please review, dogi, enhancement

#1062 convert ProfilesListAdapter to kotlin (fixes #1031)
  app/src/main/java/io/treehouses/remote/Fragments/HomeFragment.kt
  app/src/main/java/io/treehouses/remote/adapter/ProfilesListAdapter.java
  app/src/main/java/io/treehouses/remote/adapter/ProfilesListAdapter.kt
  app/src/main/java/io/treehouses/remote/utils/SaveUtils.kt
Labels: :eye: please review

#1063 tunnel: tor port list dark mode (fixes #1028)
  app/src/main/java/io/treehouses/remote/Fragments/TorTabFragment.kt
  app/src/main/res/layout/activity_tor_fragment.xml
  app/src/main/res/layout/select_dialog_item.xml
Labels: :eye: please review, enhancement

#1067 services: rounded icons in dark mode (fixes #1066)
  app/src/main/res/drawable/icon_back.xml
  app/src/main/res/layout/service_card.xml
Labels: :eye: please review, dogi, enhancement

#1053 tunnel: delete last tor port (fixes #1050)
  app/src/main/java/io/treehouses/remote/Fragments/TorTabFragment.kt
Labels: :eye: please review

#1079 terminal: dark help list (fixes #1078)
  app/src/main/res/drawable-anydpi/back_button.xml
  app/src/main/res/layout/dialog_help.xml
  app/src/main/res/layout/row_help.xml
  app/src/main/res/values-night/color.xml
  app/src/main/res/values-night/styles.xml
  app/src/main/res/values/color.xml
  app/src/main/res/values/styles.xml
Labels: :eye: please review, enhancement

#1077 services: cached loading (fixes #1076)
  app/src/main/java/io/treehouses/remote/Fragments/ServicesFragment.kt
Labels: :eye: please review, priority

#1081 terminal: dark autocomplete list (fixes #1080)
  app/src/main/java/io/treehouses/remote/bases/BaseTerminalFragment.kt
  app/src/main/res/layout/simple_dropdown_item_1line.xml
Labels: :eye: please review, enhancement

#812 ssh terminal (fixes #1091)
  .codeclimate.yml
  app/build.gradle
  app/proguard-rules.pro
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/treehouses/remote/Fragments/DialogFragments/SSHDialog.kt
  app/src/main/java/io/treehouses/remote/Fragments/SSHConsole.kt
  app/src/main/java/io/treehouses/remote/InitialActivity.kt
  app/src/main/java/io/treehouses/remote/PreferenceConstants.kt
  app/src/main/java/io/treehouses/remote/SSH/Colors.kt
  app/src/main/java/io/treehouses/remote/SSH/EcCore.kt
  app/src/main/java/io/treehouses/remote/SSH/Ed25519Provider.kt
  app/src/main/java/io/treehouses/remote/SSH/Encryptor.kt
  app/src/main/java/io/treehouses/remote/SSH/PromptHelper.kt
  app/src/main/java/io/treehouses/remote/SSH/PubKeyUtils.kt
  app/src/main/java/io/treehouses/remote/SSH/Relay.kt
  app/src/main/java/io/treehouses/remote/SSH/SSH.kt
  app/src/main/java/io/treehouses/remote/SSH/Terminal/TerminalBridge.kt
  app/src/main/java/io/treehouses/remote/SSH/Terminal/TerminalKeyListener.kt
  app/src/main/java/io/treehouses/remote/SSH/Terminal/TerminalManager.kt
  app/src/main/java/io/treehouses/remote/SSH/Terminal/TerminalTextViewOverlay.kt
  app/src/main/java/io/treehouses/remote/SSH/Terminal/TerminalView.kt
  app/src/main/java/io/treehouses/remote/SSH/Terminal/TerminalViewPager.kt
  app/src/main/java/io/treehouses/remote/SSH/beans/HostBean.kt
  app/src/main/java/io/treehouses/remote/SSH/beans/PubKeyBean.kt
  app/src/main/java/io/treehouses/remote/SSH/beans/SelectionArea.kt
  app/src/main/java/io/treehouses/remote/SSH/interfaces/BridgeDisconnectedListener.kt
  app/src/main/java/io/treehouses/remote/SSH/interfaces/FontSizeChangedListener.kt
  app/src/main/java/io/treehouses/remote/SSH/interfaces/OnHostStatusChangedListener.kt
  app/src/main/java/io/treehouses/remote/Views/terminal/Precomposer.kt
  app/src/main/java/io/treehouses/remote/Views/terminal/VDUBuffer.kt
  app/src/main/java/io/treehouses/remote/Views/terminal/VDUDisplay.kt
  app/src/main/java/io/treehouses/remote/Views/terminal/VDUInput.kt
  app/src/main/java/io/treehouses/remote/Views/terminal/vt320.kt
  app/src/main/res/anim/fade_out_delayed.xml
  app/src/main/res/anim/keyboard_fade_in.xml
  app/src/main/res/anim/keyboard_fade_out.xml
  app/src/main/res/drawable-xxhdpi/ic_keyboard.xml
  app/src/main/res/drawable-xxhdpi/ic_keyboard_arrow_down.xml
  app/src/main/res/drawable-xxhdpi/ic_keyboard_arrow_left.xml
  app/src/main/res/drawable-xxhdpi/ic_keyboard_arrow_right.xml
  app/src/main/res/drawable-xxhdpi/ic_keyboard_arrow_up.xml
  app/src/main/res/drawable-xxhdpi/ic_keyboard_hide.xml
  app/src/main/res/drawable-xxhdpi/ic_keyboard_tab.xml
  app/src/main/res/drawable-xxhdpi/keyboard_button_border.xml
  app/src/main/res/drawable-xxhdpi/keyboard_button_selector.xml
  app/src/main/res/drawable-xxhdpi/keyboard_keyboard_border.xml
  app/src/main/res/drawable/ripple.xml
  app/src/main/res/layout/activity_ssh_console.xml
  app/src/main/res/layout/dialog_ssh.xml
  app/src/main/res/layout/item_terminal.xml
  app/src/main/res/layout/keyboard.xml
  app/src/main/res/menu/activity_initial2_drawer.xml
  app/src/main/res/values/color.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/viewpager.xml
Labels: :eye: please review

#1069 tutorial: refactor (fixes #1070)
  app/src/main/java/io/treehouses/remote/Tutorials.kt
Labels: :eye: please review, refactor

#1002 status: redesign (fixes #742) (fixes #1075) (fixes #1082)
  app/src/main/java/io/treehouses/remote/Fragments/StatusFragment.kt
  app/src/main/res/drawable-xhdpi/green_progress_bar.xml
  app/src/main/res/drawable-xhdpi/red_progress_bar.xml
  app/src/main/res/drawable-xhdpi/white_rounded.xml
  app/src/main/res/drawable/ic_bluetooth.xml
  app/src/main/res/drawable/ic_update_alert.xml
  app/src/main/res/drawable/ic_wifi.xml
  app/src/main/res/drawable/lightrounded.xml
  app/src/main/res/layout/activity_status_fragment.xml
  app/src/main/res/values-night/color.xml
  app/src/main/res/values/color.xml
  app/src/main/res/values/commands.xml
Labels: :eye: please review, bug, enhancement

#1096 services: headers (fixes #1095)
  app/src/main/java/io/treehouses/remote/bases/BaseServicesFragment.kt
Labels: :eye: please review

#1071 tunnel: tor notify now button
  app/src/main/java/io/treehouses/remote/Fragments/TorTabFragment.kt
  app/src/main/res/layout/activity_tor_fragment.xml
Labels: :eye: please review

#1094 ssh: improved dialog (fixes #1093)
  app/build.gradle
  app/src/main/java/io/treehouses/remote/Fragments/DialogFragments/FeedbackDialogFragment.kt
  app/src/main/java/io/treehouses/remote/Fragments/DialogFragments/HelpDialog.kt
  app/src/main/java/io/treehouses/remote/Fragments/DialogFragments/SSHDialog.kt
  app/src/main/java/io/treehouses/remote/InitialActivity.kt
  app/src/main/java/io/treehouses/remote/bases/FullScreenDialogFragment.kt
  app/src/main/res/drawable/rectangle_border.xml
  app/src/main/res/layout/dialog_ssh.xml
  app/src/main/res/values-night/color.xml
  app/src/main/res/values/color.xml
Labels: :eye: please review

#1092 services: refactor save utils (fixes #1099)
  app/src/main/java/io/treehouses/remote/Fragments/ServicesFragment.kt
  app/src/main/java/io/treehouses/remote/utils/SaveUtils.kt
Labels: :eye: please review, refactor

#1090 terminal: selectable command description in help (fixes #1089)
  app/src/main/res/layout/dialog_help.xml
Labels: :eye: please review

#1097 terminal: highlight text in help (fixes #838)
  app/src/main/java/io/treehouses/remote/Fragments/DialogFragments/HelpDialog.kt
  app/src/main/java/io/treehouses/remote/pojo/HelpCommand.kt
Labels: :eye: please review

#1113 ssh: previous connections (fixes #1101)
  app/build.gradle
  app/proguard-rules.pro
  app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/SSHDialog.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/HomeFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/ServicesFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/SettingsFragment.kt
  app/src/main/kotlin/io/treehouses/remote/SSH/beans/HostBean.kt
  app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderSSHRow.kt
  app/src/main/kotlin/io/treehouses/remote/utils/SaveUtils.kt
  app/src/main/res/layout/dialog_ssh.xml
  app/src/main/res/layout/row_ssh.xml
  app/src/main/res/xml/app_preferences.xml
Labels: :eye: please review

#1127 ssh: refactor
  app/src/main/kotlin/io/treehouses/remote/SSH/EcCore.kt
  app/src/main/kotlin/io/treehouses/remote/SSH/Terminal/TerminalKeyListener.kt
  app/src/main/kotlin/io/treehouses/remote/SSH/Terminal/TerminalView.kt
Labels: :eye: please review, refactor

#1114 services: no empty toast (fixes #1086)
  app/src/main/kotlin/io/treehouses/remote/Fragments/ServicesDetailsFragment.kt
Labels: :eye: please review, bug

#1119 network: tutorial added (fixes #932)
  app/src/main/kotlin/io/treehouses/remote/Tutorials.kt
Labels: :eye: please review

#1109 multiverse: refactor
  app/src/main/kotlin/io/treehouses/remote/Fragments/HomeFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/SettingsFragment.kt
  app/src/main/kotlin/io/treehouses/remote/SSH/Terminal/TerminalTextViewOverlay.kt
Labels: :eye: please review

#1115 status: new tutorial (fixes #1116)
  app/src/main/kotlin/io/treehouses/remote/Tutorials.kt
Labels: :eye: please review, bug

#1118 settings: reactivate tutorials (fixes #1117)
  app/src/main/res/xml/app_preferences.xml
Labels: :eye: please review, bug

#1122 home: always unregister RPIDialog Receiver (fixes #1121)
  app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/RPIDialogFragment.kt
Labels: :eye: please review

#1074 all: rounded alert dialogs (fixes #1030) (fixes #983)
  app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/AddCommandDialogFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/ChPasswordDialogFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/RPIDialogFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/WifiDialogFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/HomeFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/NewNetworkFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/ServicesDetailsFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/ServicesFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/SettingsFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/StatusFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/TorTabFragment.kt
  app/src/main/kotlin/io/treehouses/remote/adapter/ProfilesListAdapter.kt
  app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderTether.kt
  app/src/main/kotlin/io/treehouses/remote/bases/BaseHomeFragment.kt
  app/src/main/kotlin/io/treehouses/remote/bases/BaseServicesFragment.kt
  app/src/main/kotlin/io/treehouses/remote/bases/PermissionActivity.kt
  app/src/main/res/drawable/alertdialog_background.xml
  app/src/main/res/layout/activity_rpi_dialog_fragment.xml
  app/src/main/res/layout/dialog_tor_ports.xml
  app/src/main/res/values-night/styles.xml
  app/src/main/res/values/styles.xml
Labels: :eye: please review, bug, enhancement

#1110 status: hide button once upgrading (fixes #1103)
  app/src/main/kotlin/io/treehouses/remote/Fragments/StatusFragment.kt
  build.gradle
Labels: :eye: please review

#1126 all: sync night strings (fixes #1125)
  app/src/main/res/values-night/strings.xml
Labels: :eye: please review

#1134 tutorials: shape, radius, color changes and refactor
  app/src/main/kotlin/io/treehouses/remote/Tutorials.kt
Labels: :eye: please review, enhancement, refactor

#1133 ssh: double tap completion (fixes #1132)
  app/src/main/kotlin/io/treehouses/remote/SSH/Terminal/TerminalView.kt
Labels: :eye: please review, priority

#1142 refactor
  app/src/main/kotlin/io/treehouses/remote/Fragments/HomeFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/NewNetworkFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/SSHConsole.kt
  app/src/main/kotlin/io/treehouses/remote/adapter/TunnelPageAdapter.kt
  app/src/main/kotlin/io/treehouses/remote/bases/BaseHomeFragment.kt
  app/src/main/kotlin/io/treehouses/remote/bases/BaseTerminalFragment.kt
Labels: :eye: please review, refactor

#1141 refactor
  app/src/main/kotlin/io/treehouses/remote/Fragments/SSHConsole.kt
Labels: :eye: please review

#1140 services: successful refresh (fixes #1135)
  app/src/main/kotlin/io/treehouses/remote/Fragments/ServicesFragment.kt
Labels: :eye: please review, bug

#1129 tunnel: clear tor port (fixes #1107)
  app/src/main/kotlin/io/treehouses/remote/Fragments/TorTabFragment.kt
Labels: :eye: please review

#1041 terminal: treehouses button for less typing (fixes #1144)
  app/src/main/kotlin/io/treehouses/remote/Fragments/TerminalFragment.kt
  app/src/main/kotlin/io/treehouses/remote/bases/BaseFragment.kt
  app/src/main/kotlin/io/treehouses/remote/bases/BaseTerminalFragment.kt
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/drawable/ic_green.xml
  app/src/main/res/drawable/ic_red.xml
  app/src/main/res/drawable/ic_treehouses.xml
  app/src/main/res/drawable/tree_green.xml
  app/src/main/res/drawable/tree_red.xml
  app/src/main/res/drawable/treehouses_btn.xml
  app/src/main/res/layout/activity_terminal_fragment.xml
  app/src/main/res/values-night/strings.xml
  app/src/main/res/values/strings.xml
Labels: :eye: please review, bug, enhancement

#1156 status: refresh (fixes #1153) (fixes #1154) (fixes #1155)
  app/src/main/kotlin/io/treehouses/remote/Fragments/StatusFragment.kt
  app/src/main/res/layout/activity_status_fragment.xml
Labels: :eye: please review

#1160 refactor RPIDialogFragment
  app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/RPIDialogFragment.kt
Labels: :eye: please review

#1162 refactor StatusFragment
  app/src/main/kotlin/io/treehouses/remote/Fragments/StatusFragment.kt
Labels: :eye: please review

#1161 refactor HomeFragment
  app/src/main/kotlin/io/treehouses/remote/Fragments/HomeFragment.kt
Labels: :eye: please review

#1026 tunnel: torports delete icons (fixes #1012)
  app/src/main/res/drawable/delete_icon.xml
  app/src/main/res/layout/select_dialog_item.xml
Labels: :eye: please review, priority

#1146 refactor TerminalView
  app/src/main/kotlin/io/treehouses/remote/SSH/Terminal/TerminalView.kt
Labels: :eye: please review, priority

#1159 refactor BaseHomeFragment
  app/src/main/kotlin/io/treehouses/remote/bases/BaseHomeFragment.kt
Labels: :eye: please review

#1149 refactor TerminalBridge
  app/src/main/kotlin/io/treehouses/remote/SSH/Terminal/TerminalBridge.kt
Labels: :eye: please review, priority

#1152 refactor TerminalBridge next
  app/src/main/kotlin/io/treehouses/remote/SSH/Terminal/TerminalBridge.kt
Labels: :eye: please review, priority

#972 home: activated when disconnected from everywhere
  app/src/main/kotlin/io/treehouses/remote/Fragments/HomeFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/NewNetworkFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/ServicesDetailsFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/ServicesFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/ServicesTabFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/StatusFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/SystemFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/TerminalFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/TorTabFragment.kt
  app/src/main/kotlin/io/treehouses/remote/InitialActivity.kt
  app/src/main/kotlin/io/treehouses/remote/Network/BluetoothChatService.kt
  app/src/main/kotlin/io/treehouses/remote/bases/BaseFragment.kt
  app/src/main/kotlin/io/treehouses/remote/callback/HomeInteractListener.kt
Labels: :eye: please review, priority

#1147 terminal: tutorial added for treehouses button
  app/src/main/kotlin/io/treehouses/remote/Tutorials.kt
Labels: :eye: please review

#1111 system: sshtunnel key
  app/src/main/kotlin/io/treehouses/remote/Fragments/TunnelSSHFragment.kt
  app/src/main/kotlin/io/treehouses/remote/adapter/NetworkListAdapter.kt
  app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderSSHTunnelKey.kt
  app/src/main/kotlin/io/treehouses/remote/pojo/NetworkListItem.kt
  app/src/main/kotlin/io/treehouses/remote/utils/CommandManager.kt
  app/src/main/res/layout/configure_sshtunnel_key.xml
Labels: :eye: please review

#1150 ssh: generate keys + known hosts file (fixes #1123)
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/EditHostDialog.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/SSHAllKeys.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/SSHKeyGen.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/SSHConfig.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/SettingsFragment.kt
  app/src/main/kotlin/io/treehouses/remote/InitialActivity.kt
  app/src/main/kotlin/io/treehouses/remote/SSH/Encryptor.kt
  app/src/main/kotlin/io/treehouses/remote/SSH/PubKeyUtils.kt
  app/src/main/kotlin/io/treehouses/remote/SSH/SSH.kt
  app/src/main/kotlin/io/treehouses/remote/SSH/Terminal/TerminalManager.kt
  app/src/main/kotlin/io/treehouses/remote/SSH/beans/HostBean.kt
  app/src/main/kotlin/io/treehouses/remote/SSH/beans/KnownHostBean.kt
  app/src/main/kotlin/io/treehouses/remote/SSH/beans/PubKeyBean.kt
  app/src/main/kotlin/io/treehouses/remote/SSHConsole.kt
  app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderSSHAllKeyRow.kt
  app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderSSHRow.kt
  app/src/main/kotlin/io/treehouses/remote/callback/RVButtonClick.kt
  app/src/main/kotlin/io/treehouses/remote/utils/KeyUtils.kt
  app/src/main/kotlin/io/treehouses/remote/utils/SaveUtils.kt
  app/src/main/res/drawable/ic_edit_black_24dp.xml
  app/src/main/res/layout/dialog_ssh.xml
  app/src/main/res/layout/dialog_view_keys.xml
  app/src/main/res/layout/edit_host.xml
  app/src/main/res/layout/keys_dialog.xml
  app/src/main/res/layout/row_key.xml
  app/src/main/res/layout/row_ssh.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/app_preferences.xml
Labels: :eye: please review, priority

#1167 refactor SSHConfig (fixes #1169)
  app/src/main/kotlin/io/treehouses/remote/Fragments/SSHConfig.kt
Labels: :eye: please review, priority

#1183 status: refresh tutorial added
  app/src/main/kotlin/io/treehouses/remote/Tutorials.kt
Labels: :eye: please review, dogi

#1176 refactor TerminalKeyListener
  app/src/main/kotlin/io/treehouses/remote/SSH/Terminal/TerminalKeyListener.kt
Labels: :eye: please review

#1173 system: improve wificountry (fixes #1143)
  app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderWifiCountry.kt
  app/src/main/res/layout/configure_wificountry.xml
  app/src/main/res/layout/dialog_wificountry.xml
  app/src/main/res/layout/select_dialog_item_countries.xml
Labels: :eye: please review, bug

#1177 tutorial: no duplication
  app/src/main/kotlin/io/treehouses/remote/Tutorials.kt
Labels: :eye: please review

#1166 refactor ViewHolderSSHTunnelKey
  app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderSSHTunnelKey.kt
  app/src/main/kotlin/io/treehouses/remote/bases/BaseFragment.kt
Labels: :eye: please review, priority

#1170 refactor Encryptor (fixes #1182)
  app/src/main/kotlin/io/treehouses/remote/SSH/Encryptor.kt
Labels: :eye: please review, priority

#1189 services: caching refresh (fixes #1180)
  app/src/main/kotlin/io/treehouses/remote/Fragments/ServicesFragment.kt
Labels: :eye: please review, bug

#1192 tunnel: tor add ports keyboard focus (fixes #1188)
  app/src/main/kotlin/io/treehouses/remote/Fragments/TorTabFragment.kt
Labels: :eye: please review

#1136 tunnel: sshtunnel
  app/src/main/kotlin/io/treehouses/remote/Fragments/SSHTunnelFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/TorTabFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/TunnelSSHFragment.kt
  app/src/main/kotlin/io/treehouses/remote/adapter/TunnelPageAdapter.kt
  app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderWifiCountry.kt
  app/src/main/kotlin/io/treehouses/remote/bases/BaseFragment.kt
  app/src/main/res/drawable/ic_bash.xml
  app/src/main/res/drawable/tunnel.xml
  app/src/main/res/layout/activity_tunnel_ssh_fragment.xml
  app/src/main/res/layout/dialog_sshtunnel_hosts.xml
  app/src/main/res/layout/dialog_sshtunnel_ports.xml
Labels: :eye: please review, priority

#1197 refactor SSH
  app/src/main/kotlin/io/treehouses/remote/SSH/SSH.kt
Labels: :eye: please review, dogi, priority

#1201 refactor TerminalView
  app/src/main/kotlin/io/treehouses/remote/SSH/Terminal/TerminalView.kt
Labels: :eye: please review, dogi

#1210 refactor KeyUtils
  app/src/main/kotlin/io/treehouses/remote/utils/KeyUtils.kt
Labels: :eye: please review, dogi

#1200 refactor NewNetworkFragment
  app/src/main/kotlin/io/treehouses/remote/Fragments/NewNetworkFragment.kt
Labels: :eye: please review

#1209 refactor HelpDialog
  app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/HelpDialog.kt
Labels: :eye: please review, dogi

#1216 tunnel: no duplicate sshtunnel host (fixes #1213)
  app/src/main/kotlin/io/treehouses/remote/Fragments/TunnelSSHFragment.kt
Labels: :eye: please review

#1217 home: tutorial update
  app/src/main/kotlin/io/treehouses/remote/Tutorials.kt
  app/src/main/res/layout/activity_home_fragment.xml
Labels: :eye: please review

#1187 home: new bluetooth icons
  app/src/main/kotlin/io/treehouses/remote/bases/BaseHomeFragment.kt
  app/src/main/res/drawable/bluetooth.xml
Labels: :eye: please review

#1195 refactor TerminalFragment
  app/src/main/kotlin/io/treehouses/remote/Fragments/TerminalFragment.kt
Labels: :eye: please review, priority

#1196 refactor PubKeyUtils
  app/src/main/kotlin/io/treehouses/remote/SSH/PubKeyUtils.kt
Labels: :eye: please review, priority

#1211 ssh: no duplicate keys (fixes #1203)
  app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/SSHKeyGen.kt
  app/src/main/res/layout/keys_dialog.xml
Labels: :eye: please review, priority

#1205 services: no duplication (fixes #1204) (fixes #1207)
  app/src/main/kotlin/io/treehouses/remote/Fragments/ServicesFragment.kt
Labels: :eye: please review

#1168 tunnel: tor fragment cleanup (fixes #1051)
  app/src/main/kotlin/io/treehouses/remote/Fragments/TorTabFragment.kt
  app/src/main/res/layout/activity_tor_fragment.xml
  app/src/main/res/values-night/strings.xml
  app/src/main/res/values/strings.xml
Labels: :eye: please review

#1199 services: show size in detail view (fixes #1105)
  app/proguard-rules.pro
  app/src/main/kotlin/io/treehouses/remote/Fragments/ServiceCardFragment.kt
  app/src/main/kotlin/io/treehouses/remote/bases/BaseServicesFragment.kt
  app/src/main/kotlin/io/treehouses/remote/pojo/ServiceInfo.kt
  app/src/main/kotlin/io/treehouses/remote/pojo/ServicesData.kt
  app/src/main/res/layout/service_card.xml
Labels: :eye: please review

#1225 refactor TerminalKeyListener
  app/src/main/kotlin/io/treehouses/remote/SSH/Terminal/TerminalKeyListener.kt
Labels: :eye: please review, priority

#1223 refactor SSHConsole
  app/src/main/kotlin/io/treehouses/remote/SSHConsole.kt
Labels: :eye: please review

#1222 refactor TerminalTextViewOverlay
  app/src/main/kotlin/io/treehouses/remote/SSH/Terminal/TerminalTextViewOverlay.kt
Labels: :eye: please review

#1229 network: scroll (fixes #1221)
  app/src/main/res/layout/new_network.xml
Labels: :eye: please review, bug

#1084 refactor raw commands in string resources (fixes #1083)
  app/src/main/kotlin/io/treehouses/remote/Fragments/ServicesDetailsFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/ServicesFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/ServicesTabFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/StatusFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/SystemFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/TorTabFragment.kt
  app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderBlocker.kt
  app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderCamera.kt
  app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderSSHKey.kt
  app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderVnc.kt
  app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderWifiCountry.kt
  app/src/main/kotlin/io/treehouses/remote/bases/BaseTerminalFragment.kt
  app/src/main/res/values-night/commands.xml
  app/src/main/res/values/commands.xml
Labels: :eye: please review, priority

#1226 ssh: variable bit size of sshkeys (fixes #1224)
  app/build.gradle
  app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/SSHKeyGen.kt
  app/src/main/res/layout/keys_dialog.xml
  app/src/main/res/values/strings.xml
Labels: :eye: please review, priority

#1239 refactor ViewHolderBlocker
  app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderBlocker.kt
Labels: :eye: please review, refactor

#1241 settings: redesign
  app/src/main/res/drawable/custom_pref_bottom.xml
  app/src/main/res/drawable/custom_pref_middle.xml
  app/src/main/res/drawable/custom_pref_top.xml
  app/src/main/res/drawable/custom_pref_whole.xml
  app/src/main/res/layout/custom_pref_bottom.xml
  app/src/main/res/layout/custom_pref_category.xml
  app/src/main/res/layout/custom_pref_middle.xml
  app/src/main/res/layout/custom_pref_top.xml
  app/src/main/res/layout/custom_pref_whole.xml
  app/src/main/res/values-night/color.xml
  app/src/main/res/values/color.xml
  app/src/main/res/xml/app_preferences.xml
Labels: :eye: please review, enhancement

#1245 home: no crashes (fixes #1244)
  app/src/main/kotlin/io/treehouses/remote/bases/BaseFragment.kt
Labels: :eye: please review, bug

#1243 home: no initial activity crash (fixes #1242)
  app/src/main/kotlin/io/treehouses/remote/InitialActivity.kt
Labels: :eye: please review, bug

#1234 refactor SSHConsole
  app/src/main/kotlin/io/treehouses/remote/SSHConsole.kt
Labels: :eye: please review, priority

#1236 refactor TorTabFragment
  app/src/main/kotlin/io/treehouses/remote/Fragments/TorTabFragment.kt
Labels: :eye: please review, priority
