Repository treehouses/remote, pull requests merged in 2020-08, with the labels that each got.

#1237 refactor TunnelSSHFragment
  app/src/main/kotlin/io/treehouses/remote/Fragments/TunnelSSHFragment.kt
  app/src/main/res/values/commands.xml
Labels: :eye: please review, priority, refactor

#1231 upgrade JVM target (fixes #1232)
  app/build.gradle
  app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/DeleteSSHKey.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/FeedbackDialogFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/SSHAllKeys.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/SSHKeyGen.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/SSHConfig.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/SSHTunnelFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/ServiceCardFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/TerminalFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/TextBoxValidation.kt
  app/src/main/kotlin/io/treehouses/remote/SSHConsole.kt
Labels: :eye: please review, priority, refactor

#1249 refactor ViewHolderSSHTunnelKey
  app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderSSHTunnelKey.kt
Labels: :eye: please review

#1251 refactor Services
  app/src/main/kotlin/io/treehouses/remote/Fragments/ServicesDetailsFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/ServicesFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/ServicesTabFragment.kt
  app/src/main/kotlin/io/treehouses/remote/bases/BaseServicesFragment.kt
  app/src/main/kotlin/io/treehouses/remote/utils/LogUtils.kt
Labels: :eye: please review

#1254 options: treehouses map (fixes #1253)
  app/src/main/kotlin/io/treehouses/remote/Fragments/CommunityFragment.kt
  app/src/main/kotlin/io/treehouses/remote/InitialActivity.kt
  app/src/main/kotlin/io/treehouses/remote/callback/BackPressReceiver.kt
  app/src/main/res/layout/fragment_community.xml
  app/src/main/res/menu/initial.xml
  app/src/main/res/values/strings.xml
Labels: :eye: please review, priority

#1260 network: rounded bottomsheet dialogs (fixes #1258)
  app/src/main/kotlin/io/treehouses/remote/bases/BaseBottomSheetDialog.kt
  app/src/main/res/drawable/bottomsheet_background.xml
  app/src/main/res/layout/dialog_bridge.xml
  app/src/main/res/layout/dialog_ethernet.xml
  app/src/main/res/layout/dialog_hotspot.xml
  app/src/main/res/layout/dialog_wifi.xml
  app/src/main/res/values-night/styles.xml
  app/src/main/res/values/styles.xml
Labels: :eye: please review

#1257 tunnel: tor logo re-added (fixes #1240)
  app/src/main/res/layout/activity_tor_fragment.xml
Labels: :eye: please review

#1265 terminal: adaptable color icons (fixes #1264)
  app/src/main/res/drawable/ic_history.xml
  app/src/main/res/drawable/ic_info.xml
  app/src/main/res/drawable/ic_send.xml
  app/src/main/res/layout/activity_terminal_fragment.xml
Labels: :eye: please review, enhancement

#1256 services: tutorial improvement (fixes #1255)
  app/src/main/kotlin/io/treehouses/remote/Fragments/ServicesFragment.kt
Labels: :eye: please review, bug

#1268 tunnel: add info for first time user (fixes #1267)
  app/src/main/kotlin/io/treehouses/remote/Fragments/TorTabFragment.kt
Labels: :eye: please review

#1235 home: scroll for some devices (fixes #1138)
  app/src/main/res/layout-notlong/activity_home_fragment.xml
Labels: :eye: please review

#1270 refactor SSHKeyGen
  app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/SSHKeyGen.kt
  app/src/main/kotlin/io/treehouses/remote/bases/BaseSSHKeyGen.kt
Labels: :eye: please review

#1269 refactor InitialActivity
  app/src/main/kotlin/io/treehouses/remote/InitialActivity.kt
Labels: :eye: please review

#1262 services: search in overview (fixes #980)
  app/src/main/kotlin/io/treehouses/remote/Fragments/ServicesTabFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Tutorials.kt
  app/src/main/kotlin/io/treehouses/remote/adapter/ServicesListAdapter.kt
  app/src/main/res/layout/activity_services_tab_fragment.xml
  app/src/main/res/layout/services_section_header.xml
Labels: :eye: please review

#1246 ssh: delete previous host (fixes #1212)
  app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/EditHostDialog.kt
  app/src/main/kotlin/io/treehouses/remote/utils/SaveUtils.kt
  app/src/main/res/layout/edit_host.xml
Labels: :eye: please review, question

#1277 home: no Scrollview with multiple children layout (fixes #1275)
  app/src/main/res/layout-notlong/activity_home_fragment.xml
Labels: :eye: please review, bug, priority

#1273 refactor TerminalFragment
  app/src/main/kotlin/io/treehouses/remote/Fragments/TerminalFragment.kt
Labels: :eye: please review, priority, refactor

#1280 refactor TerminalTextViewOverlay
  app/src/main/kotlin/io/treehouses/remote/SSH/Terminal/TerminalTextViewOverlay.kt
Labels: :eye: please review

#1278 refactor TerminalKeyListener
  app/src/main/kotlin/io/treehouses/remote/SSH/Terminal/TerminalKeyListener.kt
  app/src/main/kotlin/io/treehouses/remote/SSH/Terminal/TerminalView.kt
  app/src/main/kotlin/io/treehouses/remote/SSHConsole.kt
  app/src/main/kotlin/io/treehouses/remote/bases/BaseTerminalKeyListener.kt
Labels: :eye: please review, priority

#1272 refactor ServicesDetailsFragment
  app/src/main/kotlin/io/treehouses/remote/Fragments/ServicesDetailsFragment.kt
Labels: :eye: please review, priority, refactor

#1281 refactor Relay
  app/src/main/kotlin/io/treehouses/remote/SSH/Relay.kt
Labels: :eye: please review

#1263 all: text cursor transparency (fixes #1238)
  app/src/main/res/layout/activity_splash_screen.xml
  app/src/main/res/layout/dialog_ethernet.xml
  app/src/main/res/layout/dialog_feedback.xml
  app/src/main/res/layout/dialog_hotspot.xml
  app/src/main/res/layout/dialog_rename_status.xml
  app/src/main/res/layout/dialog_sshtunnel_hosts.xml
  app/src/main/res/layout/dialog_sshtunnel_ports.xml
  app/src/main/res/layout/dialog_wifi.xml
  app/src/main/res/layout/fragment_about.xml
  app/src/main/res/layout/service_card.xml
  app/src/main/res/layout/services_row_layout.xml
  app/src/main/res/values-night/styles.xml
  app/src/main/res/values/styles.xml
Labels: :eye: please review

#1282 all: rounded buttons in bottom sheet dialogs
  app/src/main/res/drawable/ic_blue.xml
  app/src/main/res/drawable/ic_grey.xml
  app/src/main/res/layout/dialog_bridge.xml
  app/src/main/res/layout/dialog_ethernet.xml
  app/src/main/res/layout/dialog_hotspot.xml
  app/src/main/res/layout/dialog_wifi.xml
Labels: :eye: please review, enhancement

#1285 terminal: help dialog design update
  app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/HelpDialog.kt
  app/src/main/res/drawable/ic_feedback_back.xml
  app/src/main/res/layout/dialog_help.xml
Labels: :eye: please review, enhancement

#1193 status: fast loading
  app/src/main/kotlin/io/treehouses/remote/Fragments/StatusFragment.kt
  app/src/main/kotlin/io/treehouses/remote/pojo/StatusData.kt
  app/src/main/res/values/commands.xml
Labels: :eye: please review

#1279 refactor TunnelSSHFragment
  app/src/main/kotlin/io/treehouses/remote/Fragments/TunnelSSHFragment.kt
Labels: :eye: please review, priority

#1284 about: new rounded feedback dialog
  app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/FeedbackDialogFragment.kt
  app/src/main/res/drawable/ic_cancel.xml
  app/src/main/res/drawable/ic_feedback_back.xml
  app/src/main/res/drawable/ic_yellow.xml
  app/src/main/res/layout/dialog_feedback.xml
Labels: :eye: please review, enhancement

#1276 refactor TerminalManager.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/SSHConfig.kt
  app/src/main/kotlin/io/treehouses/remote/SSH/SSH.kt
  app/src/main/kotlin/io/treehouses/remote/SSH/Terminal/TerminalManager.kt
  app/src/main/kotlin/io/treehouses/remote/SSHConsole.kt
Labels: :eye: please review, priority, refactor

#1297 services: no crashes (fixes #1296)
  app/src/main/kotlin/io/treehouses/remote/bases/BaseServicesFragment.kt
Labels: :eye: please review, bug

#1230 tutorials: skip functionality (fixes #1157)
  app/src/main/kotlin/io/treehouses/remote/Tutorials.kt
  app/src/main/res/layout/tutorial.xml
Labels: :eye: please review, enhancement

#1294 options: fragment title (fixes #1292) (fixes #1295)
  app/src/main/kotlin/io/treehouses/remote/InitialActivity.kt
  app/src/main/kotlin/io/treehouses/remote/utils/SaveUtils.kt
Labels: :eye: please review

#1290 settings: clear services cache (fixes #1289)
  app/src/main/kotlin/io/treehouses/remote/Fragments/SettingsFragment.kt
  app/src/main/kotlin/io/treehouses/remote/utils/SaveUtils.kt
  app/src/main/res/xml/app_preferences.xml
Labels: :eye: please review

#1291 refactor SSH
  app/src/main/kotlin/io/treehouses/remote/SSH/SSH.kt
  app/src/main/kotlin/io/treehouses/remote/bases/BaseSSH.kt
Labels: :eye: please review, priority, refactor

#1304 system: dark mode for discover (fixes #1305)
  app/src/main/kotlin/io/treehouses/remote/Fragments/DiscoverFragment.kt
  app/src/main/res/layout/activity_discover_fragment.xml
Labels: :eye: please review, enhancement

#1314 home: bottom button redesign (fixes #1313)
  app/src/main/kotlin/io/treehouses/remote/Fragments/HomeFragment.kt
  app/src/main/res/layout/activity_home_fragment.xml
Labels: :eye: please review, bug

#1312 home: no back error on dark mode
  app/src/main/kotlin/io/treehouses/remote/InitialActivity.kt
Labels: :eye: please review, bug

#1293 refactor ServicesListAdapter
  app/src/main/kotlin/io/treehouses/remote/adapter/ServicesListAdapter.kt
Labels: :eye: please review

#1311 system: improved discover link visibility (fixes #1310)
  app/src/main/res/layout/configure_discover.xml
  app/src/main/res/values/strings.xml
Labels: :eye: please review, dogi

#1306 ssh & status: refresh (fixes #1248) (fixes #1302) (fixes #1309)
  app/build.gradle
  app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/EditHostDialog.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/SSHConfig.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/StatusFragment.kt
  app/src/main/res/layout/activity_status_fragment.xml
Labels: :eye: please review, dogi, priority

#1227 tunnel: tor redesign
  app/src/main/kotlin/io/treehouses/remote/Fragments/TorTabFragment.kt
  app/src/main/res/drawable-xhdpi/trash.png
  app/src/main/res/drawable/delete_icon.xml
  app/src/main/res/drawable/gitter_button.xml
  app/src/main/res/drawable/tor_btn.xml
  app/src/main/res/layout/activity_tor_fragment.xml
  app/src/main/res/layout/dialog_tor_ports.xml
  app/src/main/res/layout/select_dialog_item.xml
  app/src/main/res/values/commands.xml
Labels: :eye: please review, dogi, enhancement, priority

#1321 home: add mvvm dependencies (fixes #1252)
  app/build.gradle
  app/src/main/kotlin/io/treehouses/remote/Fragments/NewNetworkFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/SSHTunnelFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/TerminalFragment.kt
  app/src/main/kotlin/io/treehouses/remote/InitialActivity.kt
  app/src/main/kotlin/io/treehouses/remote/ui/home/BaseHomeFragment.kt
  app/src/main/kotlin/io/treehouses/remote/ui/home/HomeFragment.kt
  app/src/main/kotlin/io/treehouses/remote/ui/home/HomeViewModel.kt
  app/src/main/kotlin/io/treehouses/remote/ui/services/BaseServicesFragment.kt
  app/src/main/kotlin/io/treehouses/remote/ui/services/ServicesDetailsFragment.kt
  app/src/main/kotlin/io/treehouses/remote/ui/services/ServicesFragment.kt
  app/src/main/kotlin/io/treehouses/remote/ui/services/ServicesOverviewFragment.kt
  app/src/main/kotlin/io/treehouses/remote/ui/services/ServicesViewModel.kt
  app/src/main/kotlin/io/treehouses/remote/utils/SaveUtils.kt
Labels: :eye: please review, priority

#1318 ssh: use string when refresh
  app/src/main/kotlin/io/treehouses/remote/Fragments/SSHConfig.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/StatusFragment.kt
Labels: :eye: please review, refactor

#1316 system: back from discover (fixes #1315)
  app/src/main/kotlin/io/treehouses/remote/Fragments/DiscoverFragment.kt
  app/src/main/kotlin/io/treehouses/remote/InitialActivity.kt
Labels: :eye: please review

#1320 status: storage bar added (fixes #1307)
  app/src/main/kotlin/io/treehouses/remote/Fragments/StatusFragment.kt
  app/src/main/kotlin/io/treehouses/remote/pojo/StatusData.kt
  app/src/main/res/drawable/blue_progress_bar.xml
  app/src/main/res/layout/activity_status_fragment.xml
Labels: :eye: please review, enhancement

#1323 refactor TerminalBridge
  app/src/main/kotlin/io/treehouses/remote/SSH/Terminal/PatternHolder.kt
  app/src/main/kotlin/io/treehouses/remote/SSH/Terminal/TerminalBridge.kt
  app/src/main/kotlin/io/treehouses/remote/bases/BaseTerminalBridge.kt
  app/src/main/kotlin/io/treehouses/remote/bases/DerivedTerminalBridge.kt
Labels: :eye: please review, priority, refactor

#1331 services: search update (fixes #1332)
  app/src/main/kotlin/io/treehouses/remote/adapter/ServicesListAdapter.kt
Labels: :eye: please review, priority

#1124 all: keep bluetooth service alive
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/io/treehouses/remote/Constants.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/RPIDialogFragment.kt
  app/src/main/kotlin/io/treehouses/remote/InitialActivity.kt
  app/src/main/kotlin/io/treehouses/remote/MainApplication.kt
  app/src/main/kotlin/io/treehouses/remote/Network/BluetoothChatService.kt
  app/src/main/kotlin/io/treehouses/remote/SplashScreenActivity.kt
  app/src/main/kotlin/io/treehouses/remote/bases/BaseFragment.kt
  app/src/main/kotlin/io/treehouses/remote/ui/home/BaseHomeFragment.kt
  app/src/main/kotlin/io/treehouses/remote/ui/home/HomeFragment.kt
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/app_preferences.xml
Labels: :eye: please review, enhancement, priority

#1322 services: add env button (fixes #1085)
  app/src/main/kotlin/io/treehouses/remote/Fragments/ServiceCardFragment.kt
  app/src/main/kotlin/io/treehouses/remote/callback/ServiceAction.kt
  app/src/main/kotlin/io/treehouses/remote/pojo/ServiceInfo.kt
  app/src/main/kotlin/io/treehouses/remote/pojo/ServicesData.kt
  app/src/main/kotlin/io/treehouses/remote/ui/services/BaseServicesFragment.kt
  app/src/main/kotlin/io/treehouses/remote/ui/services/ServicesDetailsFragment.kt
  app/src/main/res/layout/env_var.xml
  app/src/main/res/layout/env_var_item.xml
  app/src/main/res/layout/service_card.xml
Labels: :eye: please review, priority

#1333 tunnel: sshtunnel delete port (with dark mode)
  app/src/main/kotlin/io/treehouses/remote/Fragments/TunnelSSHFragment.kt
  app/src/main/res/layout/activity_tunnel_ssh_fragment.xml
Labels: :eye: please review

#1324 refactor TerminalKeyListener
  app/src/main/kotlin/io/treehouses/remote/SSH/Terminal/TerminalKeyListener.kt
Labels: :eye: please review, refactor

#1325 ssh: sshkeys instant view refresh (fixes #1303)
  app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/DeleteSSHKey.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/SSHAllKeys.kt
Labels: :eye: please review

#1329 add Vagrantfile for codeclimate (fixes #1271)
  .gitignore
  Vagrantfile
Labels: WIP

#1045 bluetooth: server script check (fixes #1020)
  .gitignore
  app/.gitignore
  app/build.gradle
  app/src/main/kotlin/io/treehouses/remote/Fragments/SettingsFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/ShowBluetoothFile.kt
  app/src/main/kotlin/io/treehouses/remote/ui/home/BaseHomeFragment.kt
  app/src/main/kotlin/io/treehouses/remote/ui/home/HomeFragment.kt
  app/src/main/kotlin/io/treehouses/remote/utils/CommandManager.kt
  app/src/main/kotlin/io/treehouses/remote/utils/Utils.kt
  app/src/main/res/layout/code_view.xml
  app/src/main/res/layout/fragment_show_bluetooth_file.xml
  app/src/main/res/xml/app_preferences.xml
  build.gradle
Labels: :eye: please review, Dont Merge, priority

#1355 home: new MVVM flow (fixes #1354)
  app/build.gradle
  app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/RPIDialogFragment.kt
  app/src/main/kotlin/io/treehouses/remote/MainApplication.kt
  app/src/main/kotlin/io/treehouses/remote/Network/BluetoothChatService.kt
  app/src/main/kotlin/io/treehouses/remote/SSH/Terminal/TerminalTextViewOverlay.kt
  app/src/main/kotlin/io/treehouses/remote/bases/BaseFragment.kt
  app/src/main/kotlin/io/treehouses/remote/bases/FragmentViewModel.kt
  app/src/main/kotlin/io/treehouses/remote/pojo/enum/Resource.kt
  app/src/main/kotlin/io/treehouses/remote/pojo/enum/Status.kt
  app/src/main/kotlin/io/treehouses/remote/ui/home/BaseHomeFragment.kt
  app/src/main/kotlin/io/treehouses/remote/ui/home/HomeFragment.kt
  app/src/main/kotlin/io/treehouses/remote/ui/home/HomeViewModel.kt
Labels: :eye: please review, priority

#1350 system: vnc switch detection (fixes #1343)
  app/src/main/kotlin/io/treehouses/remote/Fragments/SystemFragment.kt
  app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderVnc.kt
Labels: :eye: please review

#1348 network: wifi dialog dark mode (fixes #1347)
  app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/WifiDialogFragment.kt
  app/src/main/res/layout/dialog_listview.xml
  app/src/main/res/layout/simple_list_item.xml
Labels: :eye: please review

#1357 update README.md
  README.md
Labels: :eye: please review

#1368 refactor PromptHelper
  app/src/main/kotlin/io/treehouses/remote/SSH/PromptHelper.kt
Labels: :eye: please review, refactor

#1369 refactor IntroActivity
  app/src/main/kotlin/io/treehouses/remote/IntroActivity.kt
Labels: :eye: please review, refactor

#1370 refactor ShowBluetoothFile
  app/src/main/kotlin/io/treehouses/remote/Fragments/ShowBluetoothFile.kt
Labels: :eye: please review, refactor

#1372 home: internet check before server sync (fixes #1371)
  app/src/main/kotlin/io/treehouses/remote/Network/BluetoothChatService.kt
  app/src/main/kotlin/io/treehouses/remote/ui/home/BaseHomeFragment.kt
  app/src/main/kotlin/io/treehouses/remote/ui/home/HomeFragment.kt
  app/src/main/kotlin/io/treehouses/remote/ui/home/HomeViewModel.kt
Labels: :eye: please review, priority

#1367 system: discover me, android & rpis (fixes #1366, #1338, #1342)
  app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/RPIDialogFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/DiscoverFragment.kt
  app/src/main/res/drawable/android_icon.png
  app/src/main/res/drawable/raspi_logo.png
  app/src/main/res/mipmap-xxhdpi/android_icon_round.png
  app/src/main/res/mipmap-xxxhdpi/android_icon.png
  app/src/main/res/mipmap-xxxhdpi/android_icon_foreground.png
  app/src/main/res/mipmap-xxxhdpi/android_icon_round.png
  app/src/main/res/values/commands.xml
Labels: :eye: please review, enhancement, priority

#1374 tunnel: no ssh crashes (fixes #1373)
  app/src/main/kotlin/io/treehouses/remote/Fragments/TunnelSSHFragment.kt
Labels: :eye: please review, bug, priority

#1380 tunnel: ssh ports list (fixes #1379)
  app/src/main/kotlin/io/treehouses/remote/Fragments/TunnelSSHFragment.kt
Labels: :eye: please review, priority

#1360 settings: hierarchical redesign (fixes #1328, #1345, #1359)
  app/src/main/kotlin/io/treehouses/remote/Fragments/PreferenceFragments/GeneralPreference.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/PreferenceFragments/UserCustomizationPreference.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/SettingsFragment.kt
  app/src/main/kotlin/io/treehouses/remote/InitialActivity.kt
  app/src/main/kotlin/io/treehouses/remote/bases/BasePreferenceFragment.kt
  app/src/main/kotlin/io/treehouses/remote/utils/SettingsUtils.kt
  app/src/main/res/drawable-night-xxhdpi/settings_expandable_arrow.xml
  app/src/main/res/drawable-xxhdpi/settings_expandable_arrow.xml
  app/src/main/res/layout/custom_pref_whole_expandable.xml
  app/src/main/res/xml/app_preferences.xml
  app/src/main/res/xml/general_preferences.xml
  app/src/main/res/xml/user_customization_preferences.xml
Labels: :eye: please review, priority

#1390 tunnel: ssh redesign (fixes #1389)
  app/src/main/kotlin/io/treehouses/remote/Fragments/TunnelSSHFragment.kt
  app/src/main/res/layout/activity_tunnel_ssh_fragment.xml
  app/src/main/res/layout/dialog_sshtunnel_hosts.xml
  app/src/main/res/layout/dialog_sshtunnel_ports.xml
Labels: :eye: please review, enhancement, priority

#1402 update Vagrantfile (fixes #1377)
  Vagrantfile
Labels: :eye: please review, enhancement, priority

#1404 network: bottom sheet rounded dark mode (fixes #1403)
  app/src/main/res/layout/dialog_ethernet.xml
  app/src/main/res/layout/dialog_hotspot.xml
  app/src/main/res/layout/dialog_wifi.xml
Labels: :eye: please review, enhancement

#1424 tunnel: ssh ui (fixes #1423)
  app/src/main/res/layout/activity_tunnel_ssh_fragment.xml
Labels: :eye: please review, bug

#1445 system: shutdown & reboot added (fixes #1444)
  app/src/main/kotlin/io/treehouses/remote/adapter/NetworkListAdapter.kt
  app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderShutdownReboot.kt
  app/src/main/kotlin/io/treehouses/remote/pojo/NetworkListItem.kt
  app/src/main/res/drawable/restart.png
  app/src/main/res/drawable/shutdown.png
  app/src/main/res/layout/configure_shutdown_reboot.xml
  app/src/main/res/values/commands.xml
Labels: :eye: please review, enhancement

#1417 settings: toasts for SSH clearing (fixes #1415) (fixes #1416)
  app/src/main/kotlin/io/treehouses/remote/Fragments/PreferenceFragments/UserCustomizationPreference.kt
Labels: :eye: please review

#1387 discover: new router icon (fixes #1386)
  app/src/main/res/drawable/circle_white.xml
  app/src/main/res/drawable/router_icon.png
  app/src/main/res/drawable/router_icon_circle.xml
  app/src/main/res/layout/activity_discover_fragment.xml
Labels: :eye: please review, enhancement

#1385 home: bluetooth dialog corner (fixes #1384)
  app/src/main/kotlin/io/treehouses/remote/ui/home/BaseHomeFragment.kt
Labels: :eye: please review, dogi, enhancement

#1398 refactor treehouses commands overview (fixes #1397)
  app/src/main/kotlin/io/treehouses/remote/Fragments/NewNetworkFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/TunnelSSHFragment.kt
  app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderSSHTunnelKey.kt
  app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderTether.kt
  app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderVnc.kt
  app/src/main/kotlin/io/treehouses/remote/ui/home/BaseHomeFragment.kt
  app/src/main/kotlin/io/treehouses/remote/ui/services/ServicesDetailsFragment.kt
  app/src/main/kotlin/io/treehouses/remote/utils/Utils.kt
  app/src/main/res/values/commands.xml
Labels: :eye: please review, priority

#1449 status: spacing fixes (fixes #1459, #1460)
  app/src/main/kotlin/io/treehouses/remote/Fragments/StatusFragment.kt
  app/src/main/res/layout/activity_status_fragment.xml
Labels: :eye: please review, enhancement

#1448 tunnel: background (fixes #1447)
  app/src/main/res/layout/activity_ssh_tunnel_fragment.xml
  app/src/main/res/layout/activity_tunnel_ssh_fragment.xml
Labels: :eye: please review, enhancement

#1418 refactor TorTabFragment
  app/src/main/kotlin/io/treehouses/remote/Fragments/TorTabFragment.kt
Labels: :eye: please review, priority

#1433 system: discover refresh (fixes #1399)
  app/src/main/kotlin/io/treehouses/remote/Fragments/DiscoverFragment.kt
  app/src/main/res/layout/activity_discover_fragment.xml
Labels: :eye: please review, priority

#1452 tunnel: sshkey moved (fixes #1453)
  app/src/main/kotlin/io/treehouses/remote/Fragments/TunnelSSHFragment.kt
  app/src/main/kotlin/io/treehouses/remote/adapter/NetworkListAdapter.kt
  app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderSSHTunnelKey.kt
  app/src/main/kotlin/io/treehouses/remote/bases/BaseTunnelSSHFragment.kt
  app/src/main/kotlin/io/treehouses/remote/pojo/NetworkListItem.kt
  app/src/main/res/drawable/ic_key.xml
  app/src/main/res/layout/activity_tunnel_ssh_fragment.xml
  app/src/main/res/layout/dialog_sshtunnel_key.xml
Labels: :eye: please review

#1450 network: discover moved here (fixes #1442)
  app/src/main/kotlin/io/treehouses/remote/Fragments/NewNetworkFragment.kt
  app/src/main/kotlin/io/treehouses/remote/adapter/NetworkListAdapter.kt
  app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderDiscover.kt
  app/src/main/kotlin/io/treehouses/remote/pojo/NetworkListItem.kt
  app/src/main/res/layout/configure_discover.xml
  app/src/main/res/layout/new_network.xml
Labels: :eye: please review, enhancement

#1466 settings: visual feedback (fixes #1358)
  app/src/main/res/drawable-v21/custom_pref_bottom.xml
  app/src/main/res/drawable-v21/custom_pref_middle.xml
  app/src/main/res/drawable-v21/custom_pref_top.xml
  app/src/main/res/drawable-v21/custom_pref_whole.xml
Labels: :eye: please review, priority

#1462 settings: round boxes (fixes #1461)
  app/src/main/res/xml/user_customization_preferences.xml
Labels: :eye: please review, enhancement

#1482 network: discover beta text (fixes #1481)
  app/src/main/res/layout/new_network.xml
Labels: :eye: please review, enhancement

#1480 tunnel: ssh beta added in keys title (fixes #1479)
  app/src/main/res/layout/dialog_sshtunnel_key.xml
Labels: :eye: please review, enhancement

#1483 refactor services to mvvm (fixes #1439)
  app/src/main/kotlin/io/treehouses/remote/Fragments/SSHTunnelFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/ServiceCardFragment.kt
  app/src/main/kotlin/io/treehouses/remote/adapter/ServiceCardAdapter.kt
  app/src/main/kotlin/io/treehouses/remote/adapter/ServicesListAdapter.kt
  app/src/main/kotlin/io/treehouses/remote/bases/FragmentViewModel.kt
  app/src/main/kotlin/io/treehouses/remote/pojo/ServiceInfo.kt
  app/src/main/kotlin/io/treehouses/remote/ui/home/HomeViewModel.kt
  app/src/main/kotlin/io/treehouses/remote/ui/services/BaseServicesFragment.kt
  app/src/main/kotlin/io/treehouses/remote/ui/services/ServicesDetailsFragment.kt
  app/src/main/kotlin/io/treehouses/remote/ui/services/ServicesFragment.kt
  app/src/main/kotlin/io/treehouses/remote/ui/services/ServicesOverviewFragment.kt
  app/src/main/kotlin/io/treehouses/remote/ui/services/ServicesViewModel.kt
  app/src/main/kotlin/io/treehouses/remote/utils/CommandManager.kt
  app/src/main/kotlin/io/treehouses/remote/utils/ServiceHelper.kt
  app/src/main/res/values/commands.xml
Labels: :eye: please review, priority

#1455 refactor SSHConsole (fixes #1456)
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/io/treehouses/remote/Fragments/SSHConfig.kt
  app/src/main/kotlin/io/treehouses/remote/SSHConsole.kt
  app/src/main/kotlin/io/treehouses/remote/SSHConsole/BaseSSHConsole.kt
  app/src/main/kotlin/io/treehouses/remote/SSHConsole/DerivedSSHConsole.kt
  app/src/main/kotlin/io/treehouses/remote/SSHConsole/RootSSHConsole.kt
  app/src/main/kotlin/io/treehouses/remote/SSHConsole/SSHConsole.kt
  app/src/main/kotlin/io/treehouses/remote/SSHConsole/URLItemListener.kt
  app/src/main/kotlin/io/treehouses/remote/adapter/TerminalPagerAdapter.kt
  app/src/main/kotlin/io/treehouses/remote/callback/TerminalPager.kt
Labels: :eye: please review, priority

#1500 settings: show bluetooth script refactor (fixes #1393, #1499)
  app/build.gradle
  app/release/output-metadata.json
  app/src/main/kotlin/io/treehouses/remote/Fragments/ShowBluetoothFile.kt
  app/src/main/res/layout/code_view.xml
  app/src/main/res/layout/fragment_show_bluetooth_file.xml
Labels: :eye: please review, priority

#1496 refactor TerminalManager
  app/src/main/kotlin/io/treehouses/remote/SSH/Terminal/TerminalManager.kt
Labels: :eye: please review

#1495 services: improvements and cleaning up (fixes #1493, #1494)
  app/src/main/kotlin/io/treehouses/remote/Fragments/PreferenceFragments/GeneralPreference.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/ServiceCardFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Views/ServiceViewPager.kt
  app/src/main/kotlin/io/treehouses/remote/adapter/ServiceCardAdapter.kt
  app/src/main/kotlin/io/treehouses/remote/ui/services/ServicesDetailsFragment.kt
  app/src/main/kotlin/io/treehouses/remote/ui/services/ServicesFragment.kt
  app/src/main/kotlin/io/treehouses/remote/ui/services/ServicesOverviewFragment.kt
  app/src/main/kotlin/io/treehouses/remote/ui/services/ServicesViewModel.kt
  app/src/main/kotlin/io/treehouses/remote/utils/ServiceHelper.kt
  app/src/main/res/layout/activity_services_fragment.xml
Labels: :eye: please review, priority

#1489 refactor DiscoverFragment
  app/src/main/kotlin/io/treehouses/remote/Fragments/DiscoverFragment.kt
Labels: :eye: please review

#1503 services: links clickable again (fixes #1431)
  app/src/main/kotlin/io/treehouses/remote/Fragments/ServiceCardFragment.kt
Labels: :eye: please review, dogi

#1484 system: tethering redesign (fixes #1485)
  app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderTether.kt
  app/src/main/kotlin/io/treehouses/remote/pojo/NetworkListItem.kt
  app/src/main/res/drawable/ic_green2.xml
  app/src/main/res/layout/configure_tethering.xml
Labels: :eye: please review, enhancement

#1432 update README.md (fixes #1383)
  README.md
Labels: :eye: please review

#1498 refactor NetworkFragment (fixes #1497)
  app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/BottomSheetDialogs/BridgeBottomSheet.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/BottomSheetDialogs/EthernetBottomSheet.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/BottomSheetDialogs/HotspotBottomSheet.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/BottomSheetDialogs/WifiBottomSheet.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/NetworkFragment.kt
  app/src/main/kotlin/io/treehouses/remote/InitialActivity.kt
  app/src/main/kotlin/io/treehouses/remote/Tutorials.kt
  app/src/main/res/layout/activity_network_fragment.xml
Labels: :eye: please review, dogi, refactor

#1501 all: remove unneeded intent filters (fixes #1475)
  app/src/main/AndroidManifest.xml
Labels: :eye: please review

#1451 system: discover new loading animation (fixes #1437)
  app/build.gradle
  app/src/main/kotlin/io/treehouses/remote/Fragments/DiscoverFragment.kt
  app/src/main/res/drawable/wifi_searching.gif
  app/src/main/res/layout/activity_discover_fragment.xml
Labels: :eye: please review, dogi, enhancement

#1426 update travis.yml (fixes #1425)
  .travis.yml
Labels: :eye: please review

#1511 update travis.yml (fixes #1510)
  .travis.yml
Labels: WIP
