Repository treehouses/remote, pull requests merged in 2020-01, with the labels that each got.

#579 log: treehouses image version and blutooth mac address
  app/src/main/java/io/treehouses/remote/Fragments/HomeFragment.java
  app/src/main/java/io/treehouses/remote/Network/ParseDbService.java
  app/src/main/java/io/treehouses/remote/utils/Utils.java
Labels: :eye: pending review

#566 data: sharing is caring (fixes #554)
  app/src/main/res/drawable/ic_cloud_upload_black_24dp.xml
  app/src/main/res/values/strings.xml
Labels: WIP

#598 update README.md (fixes #597)
  README.md
Labels: :eye: pending review, enhancement
