Repository treehouses/remote, pull requests merged in 2020-11, with the labels that each got.

#1662 update .travis.yml (fixes #1661)
  .travis.yml
Labels: hacktoberfest-accepted

#1656 status: wificountry before upgrade (fixes #1570)
  app/src/main/kotlin/io/treehouses/remote/bases/BaseStatusFragment.kt
  app/src/main/kotlin/io/treehouses/remote/fragments/StatusFragment.kt
Labels: :eye: please review

#1610 terminal: rearrange bottom bar (fixes #1574)
  app/src/main/res/layout/activity_terminal_fragment.xml
Labels: :eye: please review

#1660 remove EcCore
  app/src/main/kotlin/io/treehouses/remote/ssh/EcCore.kt
Labels: :eye: please review

#1663 network: show ip address (fixes #1537)
  app/src/main/kotlin/io/treehouses/remote/fragments/NetworkFragment.kt
  app/src/main/kotlin/io/treehouses/remote/utils/CommandManager.kt
  app/src/main/res/layout/activity_network_fragment.xml
Labels: ready

#1668 tunnel: clearer ssh error messages (fixes #1667)
  app/src/main/kotlin/io/treehouses/remote/bases/BaseTunnelSSHFragment.kt
Labels: ready

#1666 tunnel: delete false sshport keeps button active (fixes #1641)
  app/src/main/kotlin/io/treehouses/remote/bases/BaseTunnelSSHFragment.kt
Labels: ready

#1671 status: refactor to mvvm
  app/src/main/kotlin/io/treehouses/remote/BaseInitialActivity.kt
  app/src/main/kotlin/io/treehouses/remote/MainApplication.kt
  app/src/main/kotlin/io/treehouses/remote/bases/BaseStatusFragment.kt
  app/src/main/kotlin/io/treehouses/remote/bases/FragmentViewModel.kt
  app/src/main/kotlin/io/treehouses/remote/fragments/NetworkFragment.kt
  app/src/main/kotlin/io/treehouses/remote/fragments/StatusFragment.kt
  app/src/main/kotlin/io/treehouses/remote/ui/status/StatusFragment.kt
  app/src/main/kotlin/io/treehouses/remote/ui/status/StatusViewModel.kt
Labels: :eye: please review

#1684 tunnel: ssh tutorial added (fixes #1678)
  app/src/main/kotlin/io/treehouses/remote/Tutorials.kt
  app/src/main/kotlin/io/treehouses/remote/fragments/SSHTunnelFragment.kt
  app/src/main/kotlin/io/treehouses/remote/fragments/TunnelSSHFragment.kt
Labels: :eye: please review
