Repository treehouses/remote, pull requests merged in 2020-09, with the labels that each got.

#1518 refactor BaseSSH
  app/src/main/kotlin/io/treehouses/remote/bases/BaseSSH.kt
Labels: :eye: please review

#1504 harden logs (fixes #1473)
  app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/ChPasswordDialogFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/EditHostDialog.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/RPIDialogFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/WifiDialogFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/DiscoverFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/NetworkFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/SSHConfig.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/SSHTunnelFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/ServiceCardFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/ShowBluetoothFile.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/StatusFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/SystemFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/TorTabFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/TunnelSSHFragment.kt
  app/src/main/kotlin/io/treehouses/remote/InitialActivity.kt
  app/src/main/kotlin/io/treehouses/remote/MainApplication.kt
  app/src/main/kotlin/io/treehouses/remote/Network/BluetoothChatService.kt
  app/src/main/kotlin/io/treehouses/remote/SSH/PubKeyUtils.kt
  app/src/main/kotlin/io/treehouses/remote/SSH/Relay.kt
  app/src/main/kotlin/io/treehouses/remote/SSH/SSH.kt
  app/src/main/kotlin/io/treehouses/remote/SSH/Terminal/TerminalBridge.kt
  app/src/main/kotlin/io/treehouses/remote/SSH/Terminal/TerminalKeyListener.kt
  app/src/main/kotlin/io/treehouses/remote/SSH/Terminal/TerminalManager.kt
  app/src/main/kotlin/io/treehouses/remote/SSH/Terminal/TerminalView.kt
  app/src/main/kotlin/io/treehouses/remote/SSHConsole/BaseSSHConsole.kt
  app/src/main/kotlin/io/treehouses/remote/SSHConsole/RootSSHConsole.kt
  app/src/main/kotlin/io/treehouses/remote/SSHConsole/SSHConsole.kt
  app/src/main/kotlin/io/treehouses/remote/SSHConsole/URLItemListener.kt
  app/src/main/kotlin/io/treehouses/remote/adapter/ServicesListAdapter.kt
  app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderBlocker.kt
  app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderSSHKey.kt
  app/src/main/kotlin/io/treehouses/remote/bases/BaseFragment.kt
  app/src/main/kotlin/io/treehouses/remote/bases/BaseSSH.kt
  app/src/main/kotlin/io/treehouses/remote/bases/BaseSSHKeyGen.kt
  app/src/main/kotlin/io/treehouses/remote/bases/BaseTerminalBridge.kt
  app/src/main/kotlin/io/treehouses/remote/bases/BaseTerminalFragment.kt
  app/src/main/kotlin/io/treehouses/remote/bases/BaseTerminalKeyListener.kt
  app/src/main/kotlin/io/treehouses/remote/bases/BaseTunnelSSHFragment.kt
  app/src/main/kotlin/io/treehouses/remote/bases/DerivedTerminalBridge.kt
  app/src/main/kotlin/io/treehouses/remote/bases/FragmentViewModel.kt
  app/src/main/kotlin/io/treehouses/remote/ui/home/BaseHomeFragment.kt
  app/src/main/kotlin/io/treehouses/remote/ui/home/HomeFragment.kt
  app/src/main/kotlin/io/treehouses/remote/ui/home/HomeViewModel.kt
  app/src/main/kotlin/io/treehouses/remote/ui/services/ServicesDetailsFragment.kt
  app/src/main/kotlin/io/treehouses/remote/ui/services/ServicesFragment.kt
  app/src/main/kotlin/io/treehouses/remote/ui/services/ServicesViewModel.kt
  app/src/main/kotlin/io/treehouses/remote/utils/GPSService.kt
  app/src/main/kotlin/io/treehouses/remote/utils/KeyUtils.kt
  app/src/main/kotlin/io/treehouses/remote/utils/LogUtils.kt
  app/src/main/kotlin/io/treehouses/remote/utils/SaveUtils.kt
  app/src/main/kotlin/io/treehouses/remote/utils/SettingsUtils.kt
Labels: :eye: please review, newbie friendly, priority

#1502 options: no data no community map (fixes #1266)
  app/src/main/kotlin/io/treehouses/remote/InitialActivity.kt
  app/src/main/res/drawable/community_map.png
  app/src/main/res/layout/alert_log_map.xml
Labels: :eye: please review

#1490 status: wificountry (fixes #1491)
  app/src/main/kotlin/io/treehouses/remote/Fragments/StatusFragment.kt
  app/src/main/kotlin/io/treehouses/remote/adapter/NetworkListAdapter.kt
  app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderWifiCountry.kt
  app/src/main/kotlin/io/treehouses/remote/bases/BaseStatusFragment.kt
  app/src/main/kotlin/io/treehouses/remote/pojo/NetworkListItem.kt
  app/src/main/res/layout/activity_status_fragment.xml
  app/src/main/res/layout/configure_wificountry.xml
Labels: :eye: please review, enhancement, refactor

#1522 tunnel: dialog close buttons (fixes #1508, #1521)
  app/src/main/kotlin/io/treehouses/remote/Fragments/TorTabFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/TunnelSSHFragment.kt
  app/src/main/res/layout/dialog_sshtunnel_hosts.xml
  app/src/main/res/layout/dialog_sshtunnel_ports.xml
  app/src/main/res/layout/dialog_tor_ports.xml
Labels: :eye: please review

#1529 status: ready for new json (fixes #1528)
  app/src/main/kotlin/io/treehouses/remote/Fragments/StatusFragment.kt
  app/src/main/kotlin/io/treehouses/remote/bases/BaseStatusFragment.kt
  app/src/main/kotlin/io/treehouses/remote/pojo/StatusData.kt
Labels: :eye: please review

#1514 refactor PubKeyUtils
  app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/SSHAllKeys.kt
  app/src/main/kotlin/io/treehouses/remote/SSH/PubKeyUtils.kt
  app/src/main/kotlin/io/treehouses/remote/SSH/SSH.kt
Labels: :eye: please review

#1506 refactor bluetoothChatService
  app/src/main/kotlin/io/treehouses/remote/Network/BluetoothChatService.kt
  app/src/main/kotlin/io/treehouses/remote/bases/BaseBluetoothChatService.kt
Labels: :eye: please review, refactor

#1533 system: no crashes in open vnc (fixes #1530, #1532)
  app/src/main/kotlin/io/treehouses/remote/Fragments/SystemFragment.kt
  app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderTether.kt
Labels: :eye: please review, bug, priority

#1535 home: no multiple asks for bluetooth sync
  app/src/main/kotlin/io/treehouses/remote/ui/home/BaseHomeFragment.kt
  app/src/main/kotlin/io/treehouses/remote/ui/home/HomeFragment.kt
  app/src/main/res/values/commands.xml
Labels: :eye: please review, bug, priority

#1505 refactor TerminalView
  app/src/main/kotlin/io/treehouses/remote/SSH/Terminal/BaseTerminalView.kt
  app/src/main/kotlin/io/treehouses/remote/SSH/Terminal/TerminalView.kt
Labels: :eye: please review, priority, refactor

#1523 tunnel: better wording in tor (fixes #1516)
  app/src/main/kotlin/io/treehouses/remote/Fragments/TorTabFragment.kt
Labels: :eye: please review

#1515 tunnel: tor gitter button improved (fixes #1507)
  app/src/main/kotlin/io/treehouses/remote/Fragments/TorTabFragment.kt
Labels: :eye: please review, priority

#1542 services: no broken svg (fixes #1541)
  app/src/main/kotlin/io/treehouses/remote/ui/services/ServicesViewModel.kt
Labels: :eye: please review, bug, priority

#1536 refactor InitialActivity
  app/src/main/kotlin/io/treehouses/remote/BaseInitialActivity.kt
  app/src/main/kotlin/io/treehouses/remote/InitialActivity.kt
  app/src/main/kotlin/io/treehouses/remote/ui/home/BaseHomeFragment.kt
  app/src/main/kotlin/io/treehouses/remote/ui/home/HomeFragment.kt
  app/src/main/kotlin/io/treehouses/remote/utils/DialogUtils.kt
Labels: :eye: please review, priority

#1534 system: toggle camera redesign (fixes #1531)
  app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderCamera.kt
  app/src/main/res/layout/configure_camera.xml
Labels: :eye: please review, priority

#1478 system: blocker redesign (fixes #1477)
  app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderBlocker.kt
  app/src/main/kotlin/io/treehouses/remote/pojo/NetworkListItem.kt
  app/src/main/res/layout/configure_blocker.xml
Labels: :eye: please review, enhancement

#1540 ssh: easy access for send key to server (fixes #1539)
  app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/SSHAllKeys.kt
  app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderSSHAllKeyRow.kt
  app/src/main/kotlin/io/treehouses/remote/callback/KeyMenuListener.kt
  app/src/main/res/menu/keys_menu.xml
  app/src/main/res/values/commands.xml
Labels: :eye: please review

#1527 system: add ssh key redesign (fixes #1526)
  app/src/main/res/layout/configure_ssh_key.xml
Labels: :eye: please review

#1525 system: open vnc redesign (fixes #1524)
  app/src/main/res/layout/layout_btn_configuration.xml
  app/src/main/res/layout/open_vnc.xml
Labels: :eye: please review

#1552 refactor multiple Dialogs
  app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/AddCommandDialogFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/RPIDialogFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/WifiDialogFragment.kt
  app/src/main/kotlin/io/treehouses/remote/InitialActivity.kt
  app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderTether.kt
  app/src/main/kotlin/io/treehouses/remote/ui/home/BaseHomeFragment.kt
  app/src/main/kotlin/io/treehouses/remote/utils/DialogUtils.kt
Labels: :eye: please review, priority

#1554 refactor BaseTunnelSSHFragment and other Toasts
  app/src/main/kotlin/io/treehouses/remote/Fragments/NetworkFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/TorTabFragment.kt
  app/src/main/kotlin/io/treehouses/remote/bases/BaseTunnelSSHFragment.kt
  app/src/main/kotlin/io/treehouses/remote/utils/Utils.kt
Labels: :eye: please review, priority

#1555 refactor BluetoothChatService
  app/src/main/kotlin/io/treehouses/remote/Network/BluetoothChatService.kt
  app/src/main/kotlin/io/treehouses/remote/bases/BaseBluetoothChatService.kt
Labels: :eye: please review, priority

#1558 home: only show dialog if device is not null (fixes #1553)
  app/src/main/kotlin/io/treehouses/remote/ui/home/HomeFragment.kt
Labels: :eye: please review, priority

#1559 status: refresh after upgrade reactivated (fixes #1550)
  app/src/main/kotlin/io/treehouses/remote/bases/BaseStatusFragment.kt
Labels: :eye: please review, priority

#1454 about: button visual feedback when clicked (fixes #1396)
  app/src/main/kotlin/io/treehouses/remote/Fragments/AboutFragment.kt
  app/src/main/res/drawable/ic_about_btn.xml
  app/src/main/res/drawable/ic_about_btn_pressed.xml
Labels: :eye: please review

#1548 system: ssh 2fa redesign (fixes #1545, #1547)
  app/src/main/res/layout/configure_ssh2fa.xml
Labels: :eye: please review

#1561 menu: visual feedback when selected (fixes #1560)
  app/src/main/res/drawable-anydpi/navigation_menu_bg.xml
Labels: :eye: please review

#1549 tunnel: add ssh key dialog close button (fixes #1546)
  app/src/main/kotlin/io/treehouses/remote/Fragments/TunnelSSHFragment.kt
  app/src/main/res/layout/dialog_sshtunnel_key.xml
Labels: :eye: please review

#1557 services: scroll on service card when necessary (fixes #1556)
  app/src/main/res/layout/service_card.xml
Labels: :eye: please review

#1487 network: tutorial for discover button (fixes #1486)
  app/src/main/kotlin/io/treehouses/remote/Tutorials.kt
Labels: :eye: please review, enhancement

#1581 all: remove backup permission (fixes #1520)
  app/src/main/AndroidManifest.xml
Labels: :eye: please review

#1578 system: share internet improvements (fixes #1563, #1576, #1577)
  app/src/main/kotlin/io/treehouses/remote/Fragments/SystemFragment.kt
  app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderTether.kt
  app/src/main/kotlin/io/treehouses/remote/utils/DialogUtils.kt
Labels: :eye: please review

#1590 refactor ServicesDetailsFragment
  app/src/main/kotlin/io/treehouses/remote/ui/services/BaseServicesDetailsFragment.kt
  app/src/main/kotlin/io/treehouses/remote/ui/services/ServicesDetailsFragment.kt
Labels: :eye: please review

#1317 tunnel: socks
  app/src/main/kotlin/io/treehouses/remote/Fragments/SocksFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/TorTabFragment.kt
  app/src/main/kotlin/io/treehouses/remote/adapter/TunnelPageAdapter.kt
  app/src/main/res/drawable/ic_shadowsocks_logo.xml
  app/src/main/res/layout/activity_socks_fragment.xml
  app/src/main/res/layout/activity_ssh_tunnel_fragment.xml
  app/src/main/res/layout/dialog_add_profile.xml
  app/src/main/res/values/strings.xml
Labels: :eye: please review

#1580 system: add confirmations (fixes #1551, #1583)
  app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/AddCommandDialogFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/RPIDialogFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/WifiDialogFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/SystemFragment.kt
  app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderShutdownReboot.kt
  app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderTether.kt
  app/src/main/kotlin/io/treehouses/remote/ui/home/BaseHomeFragment.kt
  app/src/main/kotlin/io/treehouses/remote/utils/DialogUtils.kt
Labels: :eye: please review, priority

#1592 refactor PromptHelper
  app/src/main/kotlin/io/treehouses/remote/SSH/PromptHelper.kt
  app/src/main/kotlin/io/treehouses/remote/SSH/SSH.kt
  app/src/main/kotlin/io/treehouses/remote/SSH/Terminal/TerminalBridge.kt
  app/src/main/kotlin/io/treehouses/remote/bases/BaseSSH.kt
Labels: :eye: please review

#1582 refactor duplication
  app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/DeleteSSHKey.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/EditHostDialog.kt
  app/src/main/kotlin/io/treehouses/remote/SSH/Terminal/TerminalViewPager.kt
Labels: :eye: please review

#1591 tunnel: tor delete all ports (fixes #1565)
  app/src/main/kotlin/io/treehouses/remote/Fragments/TorTabFragment.kt
  app/src/main/kotlin/io/treehouses/remote/adapter/TunnelPortAdapter.kt
  app/src/main/kotlin/io/treehouses/remote/utils/DialogUtils.kt
  app/src/main/res/drawable/delete_all_icon.xml
  app/src/main/res/layout/activity_tor_fragment.xml
  app/src/main/res/layout/select_dialog_item_delete_all.xml
  app/src/main/res/values-night/strings.xml
  app/src/main/res/values/commands.xml
  app/src/main/res/values/strings.xml
Labels: :eye: please review

#1599 refactor Dialogs
  app/src/main/kotlin/io/treehouses/remote/Fragments/StatusFragment.kt
  app/src/main/kotlin/io/treehouses/remote/InitialActivity.kt
  app/src/main/kotlin/io/treehouses/remote/ui/home/BaseHomeFragment.kt
  app/src/main/kotlin/io/treehouses/remote/ui/services/ServicesDetailsFragment.kt
  app/src/main/kotlin/io/treehouses/remote/utils/DialogUtils.kt
Labels: :eye: please review, priority

#1597 refactor TorTabFragment
  app/src/main/kotlin/io/treehouses/remote/Fragments/TorTabFragment.kt
  app/src/main/kotlin/io/treehouses/remote/bases/BaseTorTabFragment.kt
Labels: :eye: please review, priority

#1603 refactor TerminalKeyListener
  app/src/main/kotlin/io/treehouses/remote/SSH/Terminal/TerminalKeyListener.kt
Labels: :eye: please review

#1598 refactor ViewHolderCamera
  app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderCamera.kt
Labels: :eye: please review

#1604 refactor ViewHolderShutdownReboot
  app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderShutdownReboot.kt
Labels: :eye: please review

#1606 options: auto open community (fixes #1602)
  app/src/main/kotlin/io/treehouses/remote/InitialActivity.kt
Labels: :eye: please review

#1618 ssh: make password input work again (fixes #1617)
  app/src/main/kotlin/io/treehouses/remote/SSH/PromptHelper.kt
Labels: bug, priority

#1621 ssh: make ssh host detection work again (fixes #1617)
  app/src/main/kotlin/io/treehouses/remote/SSH/PromptHelper.kt
  app/src/main/kotlin/io/treehouses/remote/SSH/SSH.kt
  app/src/main/kotlin/io/treehouses/remote/SSH/Terminal/TerminalBridge.kt
  app/src/main/kotlin/io/treehouses/remote/bases/BaseSSH.kt
Labels: :eye: please review, bug, priority

#1613 refactor unused variables
  app/src/main/kotlin/io/treehouses/remote/Fragments/StatusFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/TerminalFragment.kt
  app/src/main/kotlin/io/treehouses/remote/SSH/Terminal/TerminalKeyListener.kt
  app/src/main/kotlin/io/treehouses/remote/Tutorials.kt
  app/src/main/kotlin/io/treehouses/remote/Views/terminal/vt320.kt
  app/src/main/kotlin/io/treehouses/remote/bases/BaseSSH.kt
  app/src/main/kotlin/io/treehouses/remote/bases/BaseTerminalFragment.kt
  app/src/main/kotlin/io/treehouses/remote/bases/BaseTerminalKeyListener.kt
  app/src/main/kotlin/io/treehouses/remote/utils/KeyUtils.kt
  app/src/main/kotlin/io/treehouses/remote/utils/LogUtils.kt
Labels: :eye: please review

#1614 refactor shadowed variables
  app/src/main/kotlin/io/treehouses/remote/SSH/Terminal/TerminalManager.kt
  app/src/main/kotlin/io/treehouses/remote/Views/terminal/VDUBuffer.kt
  app/src/main/kotlin/io/treehouses/remote/Views/terminal/vt320.kt
  app/src/main/kotlin/io/treehouses/remote/adapter/CommandListAdapter.kt
  app/src/main/kotlin/io/treehouses/remote/adapter/NetworkListAdapter.kt
  app/src/main/kotlin/io/treehouses/remote/adapter/ProfilesListAdapter.kt
  app/src/main/kotlin/io/treehouses/remote/adapter/RPIListAdapter.kt
Labels: :eye: please review

#1616 refactor DeleteSSHKey no warnings
  app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/DeleteSSHKey.kt
Labels: :eye: please review

#1615 refactor HomeViewModel remove warnings
  app/src/main/kotlin/io/treehouses/remote/ui/home/HomeViewModel.kt
Labels: :eye: please review

#1626 services: redesign open url dialog (fixes #1468, #1544)
  app/src/main/kotlin/io/treehouses/remote/ui/services/BaseServicesDetailsFragment.kt
  app/src/main/res/drawable/ic_purple.xml
  app/src/main/res/layout/dialog_choose_url.xml
Labels: :eye: please review

#1625 about: feedback button with visual feedback (fixes #1624)
  app/src/main/res/drawable/ic_give_feedback.xml
  app/src/main/res/drawable/ic_give_feedback_button_pressed.xml
Labels: :eye: please review

#1628 refactor SaveUtils
  app/src/main/kotlin/io/treehouses/remote/ui/services/ServicesViewModel.kt
  app/src/main/kotlin/io/treehouses/remote/utils/SaveUtils.kt
  app/src/main/kotlin/io/treehouses/remote/utils/Utils.kt
  app/src/main/res/values-night/strings.xml
  app/src/main/res/values/strings.xml
Labels: :eye: please review, priority

#1631 refactor ServicesViewModel
  app/src/main/kotlin/io/treehouses/remote/ui/services/ServicesViewModel.kt
Labels: :eye: please review

#1630 refactor ServicesListAdapter
  app/src/main/kotlin/io/treehouses/remote/adapter/ServicesListAdapter.kt
Labels: :eye: please review

#1632 refactor TerminalViewPager
  app/src/main/kotlin/io/treehouses/remote/SSH/Terminal/TerminalViewPager.kt
Labels: :eye: please review

#1629 refactor ServiceViewPager
  app/src/main/kotlin/io/treehouses/remote/Views/ServiceViewPager.kt
Labels: :eye: please review

#1634 refactor EditHostDialog
  app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/ChPasswordDialogFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/EditHostDialog.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/DiscoverFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/NetworkFragment.kt
  app/src/main/kotlin/io/treehouses/remote/Interfaces/FragmentDialogInterface.kt
Labels: :eye: please review

#1627 refactor HomeFragment
  app/src/main/kotlin/io/treehouses/remote/Fragments/StatusFragment.kt
  app/src/main/kotlin/io/treehouses/remote/ui/home/HomeFragment.kt
  app/src/main/kotlin/io/treehouses/remote/utils/Utils.kt
Labels: :eye: please review

#1633 refactor TunnelSSHFragment
  app/src/main/kotlin/io/treehouses/remote/Fragments/TunnelSSHFragment.kt
  app/src/main/kotlin/io/treehouses/remote/bases/BaseTorTabFragment.kt
  app/src/main/kotlin/io/treehouses/remote/utils/TunnelUtils.kt
Labels: :eye: please review

#1638 terminal: roundify add command button (fixes #1637)
  app/src/main/res/drawable/add_command_background.xml
Labels: :eye: please review

#1644 refactor BaseTerminalFragment
  app/src/main/kotlin/io/treehouses/remote/bases/BaseTerminalFragment.kt
Labels: :eye: please review

#1636 ssh: smart connect (fixes #1607, #1608, #1635)
  app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/SSHAllKeys.kt
  app/src/main/kotlin/io/treehouses/remote/Fragments/SSHConfig.kt
  app/src/main/kotlin/io/treehouses/remote/utils/KeyUtils.kt
  app/src/main/res/drawable/green_ripple.xml
  app/src/main/res/layout/dialog_ssh.xml
Labels: :eye: please review, priority
