Repository treehouses/remote, pull requests merged in 2020-06, with the labels that each got.

#817 system: refactor NetworkListAdapter
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/treehouses/remote/adapter/NetworkListAdapter.java
Labels: refactor

#837 network: new open wifi matcher (#836)
  app/src/main/java/io/treehouses/remote/utils/CommandManager.kt
Labels: bug, priority

#832 convert SetDisconnect and DeviceInfo to kotlin
  app/src/main/java/io/treehouses/remote/callback/SetDisconnect.java
  app/src/main/java/io/treehouses/remote/callback/SetDisconnect.kt
  app/src/main/java/io/treehouses/remote/pojo/DeviceInfo.java
  app/src/main/java/io/treehouses/remote/pojo/DeviceInfo.kt
Labels: dogi

#821 refactor ServiceViewPager
  app/src/main/java/io/treehouses/remote/Views/ServiceViewPager.java
Labels: dogi, refactor

#834 convert LogUtils to kotlin
  app/src/main/java/io/treehouses/remote/utils/LogUtils.java
  app/src/main/java/io/treehouses/remote/utils/LogUtils.kt
Labels: dogi

#835 convert VersionUtils to kotlin
  app/src/main/java/io/treehouses/remote/utils/VersionUtils.java
  app/src/main/java/io/treehouses/remote/utils/VersionUtils.kt
Labels: dogi

#833 convert ServiceInfo to kotlin
  app/src/main/java/io/treehouses/remote/pojo/ServiceInfo.java
  app/src/main/java/io/treehouses/remote/pojo/ServiceInfo.kt
Labels: dogi

#842 home: add hidden wifi/hotspot profiles (fixes #841)
  app/src/main/java/io/treehouses/remote/Fragments/DialogFragments/BottomSheetDialogs/HotspotBottomSheet.kt
  app/src/main/java/io/treehouses/remote/Fragments/DialogFragments/BottomSheetDialogs/WifiBottomSheet.kt
  app/src/main/java/io/treehouses/remote/Fragments/HomeFragment.kt
  app/src/main/java/io/treehouses/remote/pojo/NetworkProfile.java
  app/src/main/java/io/treehouses/remote/utils/SaveUtils.java
  app/src/main/res/layout/dialog_hotspot.xml
Labels: :eye: please review

#823 refactor BaseServicesFragment
  app/src/main/java/io/treehouses/remote/bases/BaseServicesFragment.java
Labels: :eye: please review, refactor

#822 refactor ServicesDetailsFragment
  app/src/main/java/io/treehouses/remote/Fragments/ServicesDetailsFragment.java
Labels: :eye: please review, refactor

#844 network: white text on bottom sheet fix (fixes #840)
  app/src/main/res/layout/dialog_bridge.xml
  app/src/main/res/layout/dialog_ethernet.xml
  app/src/main/res/layout/dialog_hotspot.xml
  app/src/main/res/layout/dialog_wifi.xml
Labels: :eye: please review, bug, priority

#846 settings: dark mode set to automatic as default (fixes #845)
  app/src/main/java/io/treehouses/remote/Fragments/SettingsFragment.kt
  app/src/main/java/io/treehouses/remote/SplashScreenActivity.kt
  app/src/main/res/values-night/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/app_preferences.xml
Labels: :eye: please review

#850 terminal: reboot redirect to home (fixes #795)
  app/src/main/java/io/treehouses/remote/Fragments/TerminalFragment.kt
Labels: :eye: please review

#849 network: wpa2 enterprise wifi added (fixes #848)
  app/src/main/java/io/treehouses/remote/Fragments/DialogFragments/BottomSheetDialogs/WifiBottomSheet.kt
  app/src/main/res/layout/dialog_wifi.xml
  app/src/main/res/values-night/commands.xml
  app/src/main/res/values/commands.xml
Labels: :eye: please review

#855 convert ServiceViewPager to kotlin
  app/src/main/java/io/treehouses/remote/Views/ServiceViewPager.java
  app/src/main/java/io/treehouses/remote/Views/ServiceViewPager.kt
Labels: :eye: please review

#857 convert ServicesDetailFragment to kotlin and refactor
  app/src/main/java/io/treehouses/remote/Fragments/ServicesDetailsFragment.java
  app/src/main/java/io/treehouses/remote/Fragments/ServicesDetailsFragment.kt
Labels: :eye: please review

#856 convert ServiceCardFragment to kotlin
  app/src/main/java/io/treehouses/remote/Fragments/ServiceCardFragment.java
  app/src/main/java/io/treehouses/remote/Fragments/ServiceCardFragment.kt
Labels: :eye: please review

#839 convert Utils to kotlin
  app/src/main/java/io/treehouses/remote/bases/BaseTerminalFragment.kt
  app/src/main/java/io/treehouses/remote/utils/Utils.java
  app/src/main/java/io/treehouses/remote/utils/Utils.kt
Labels: :eye: please review

#858 convert SystemFragment to kotlin
  app/src/main/java/io/treehouses/remote/Fragments/SystemFragment.java
  app/src/main/java/io/treehouses/remote/Fragments/SystemFragment.kt
Labels: :eye: please review

#843 bluetooth disconnect error handling (fixes #829)
  app/src/main/java/io/treehouses/remote/Network/BluetoothChatService.java
Labels: :eye: please review

#862 fdroid: fastlane directory added (fixes #861)
  fastlane/metadata/android/en-US/full_description.txt
  fastlane/metadata/android/en-US/images/icon.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/1.PNG
  fastlane/metadata/android/en-US/images/phoneScreenshots/2.PNG
  fastlane/metadata/android/en-US/images/phoneScreenshots/3.PNG
  fastlane/metadata/android/en-US/images/phoneScreenshots/4.PNG
  fastlane/metadata/android/en-US/images/phoneScreenshots/5.PNG
  fastlane/metadata/android/en-US/images/phoneScreenshots/6.PNG
  fastlane/metadata/android/en-US/images/phoneScreenshots/7.PNG
  fastlane/metadata/android/en-US/images/phoneScreenshots/8.PNG
  fastlane/metadata/android/en-US/images/phoneScreenshots/9.PNG
  fastlane/metadata/android/en-US/short_description.txt
  fastlane/metadata/android/en-US/title.txt
Labels: :eye: please review, priority

#859 fdroid: literal values of versionCode and versionName
  app/build.gradle
Labels: :eye: please review, priority

#869 dark mode in refactored AlertDialog's (fixes #852)
  app/src/main/java/io/treehouses/remote/Fragments/DialogFragments/AddCommandDialogFragment.java
  app/src/main/java/io/treehouses/remote/Fragments/DialogFragments/ChPasswordDialogFragment.java
  app/src/main/java/io/treehouses/remote/Fragments/DialogFragments/WifiDialogFragment.java
  app/src/main/java/io/treehouses/remote/Fragments/HomeFragment.kt
  app/src/main/java/io/treehouses/remote/Fragments/NewNetworkFragment.kt
  app/src/main/java/io/treehouses/remote/Fragments/ServicesDetailsFragment.kt
  app/src/main/java/io/treehouses/remote/Fragments/ServicesFragment.java
  app/src/main/java/io/treehouses/remote/Fragments/SettingsFragment.kt
  app/src/main/java/io/treehouses/remote/Fragments/StatusFragment.kt
  app/src/main/java/io/treehouses/remote/InitialActivity.kt
  app/src/main/java/io/treehouses/remote/adapter/ProfilesListAdapter.java
  app/src/main/java/io/treehouses/remote/adapter/ViewHolderTether.java
  app/src/main/java/io/treehouses/remote/bases/BaseHomeFragment.kt
  app/src/main/java/io/treehouses/remote/bases/BaseServicesFragment.java
  app/src/main/java/io/treehouses/remote/bases/PermissionActivity.kt
  app/src/main/java/io/treehouses/remote/utils/GPSService.java
  app/src/main/res/layout/chpass_dialog.xml
  app/src/main/res/layout/dialog_add_command.xml
  app/src/main/res/layout/dialog_bridge.xml
  app/src/main/res/layout/dialog_ethernet.xml
  app/src/main/res/layout/dialog_hotspot.xml
  app/src/main/res/layout/dialog_rename_status.xml
  app/src/main/res/layout/dialog_wifi.xml
  app/src/main/res/values-night/styles.xml
  app/src/main/res/values/styles.xml
Labels: :eye: please review, priority

#867 convert CommandListAdapter to kotlin
  app/src/main/java/io/treehouses/remote/Fragments/TerminalFragment.kt
  app/src/main/java/io/treehouses/remote/adapter/CommandListAdapter.java
  app/src/main/java/io/treehouses/remote/adapter/CommandListAdapter.kt
Labels: :eye: please review

#866 convert TextBoxValidation to kotlin
  app/src/main/java/io/treehouses/remote/Fragments/DialogFragments/BottomSheetDialogs/BridgeBottomSheet.kt
  app/src/main/java/io/treehouses/remote/Fragments/DialogFragments/BottomSheetDialogs/WifiBottomSheet.kt
  app/src/main/java/io/treehouses/remote/Fragments/TextBoxValidation.java
  app/src/main/java/io/treehouses/remote/Fragments/TextBoxValidation.kt
Labels: :eye: please review

#761 tunnel: redesign tor (fixes #540)
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/treehouses/remote/Fragments/DialogFragments/BottomSheetDialogs/TorBottomSheet.java
  app/src/main/java/io/treehouses/remote/Fragments/SSHTunnelFragment.java
  app/src/main/java/io/treehouses/remote/Fragments/TorTabFragment.java
  app/src/main/java/io/treehouses/remote/Fragments/TunnelFragment.java
  app/src/main/java/io/treehouses/remote/Fragments/TunnelSSHFragment.java
  app/src/main/java/io/treehouses/remote/InitialActivity.kt
  app/src/main/java/io/treehouses/remote/Views/TunnelViewPager.java
  app/src/main/java/io/treehouses/remote/adapter/TunnelPageAdapter.java
  app/src/main/res/drawable/tor.xml
  app/src/main/res/layout/activity_ssh_tunnel_fragment.xml
  app/src/main/res/layout/activity_tor_fragment.xml
  app/src/main/res/layout/activity_tunnel_fragment.xml
  app/src/main/res/layout/activity_tunnel_ssh_fragment.xml
  app/src/main/res/layout/dialog_tor.xml
  app/src/main/res/layout/dialog_tor_ports.xml
  app/src/main/res/menu/activity_initial2_drawer.xml
  app/src/main/res/values/strings.xml
Labels: :eye: please review, priority

#891 terminal: open from menu
  app/src/main/java/io/treehouses/remote/InitialActivity.kt
Labels: priority

#887 splash: dark mode (fixes #886)
  app/src/main/res/layout/activity_splash_screen.xml
Labels: :eye: please review, priority

#895 services: no page crash (fixes #894)
  app/build.gradle
  app/src/main/java/io/treehouses/remote/Fragments/ServiceCardFragment.kt
  app/src/main/java/io/treehouses/remote/Fragments/ServicesDetailsFragment.kt
Labels: priority

#888 convert WifiDialogFragment to kotlin
  app/src/main/java/io/treehouses/remote/Fragments/DialogFragments/WifiDialogFragment.java
  app/src/main/java/io/treehouses/remote/Fragments/DialogFragments/WifiDialogFragment.kt
Labels: :eye: please review

#889 convert AddCommandDialogFragment to kotlin
  app/src/main/java/io/treehouses/remote/Fragments/DialogFragments/AddCommandDialogFragment.java
  app/src/main/java/io/treehouses/remote/Fragments/DialogFragments/AddCommandDialogFragment.kt
Labels: :eye: please review

#890 convert HomeInteractListener to kotlin
  app/src/main/java/io/treehouses/remote/Fragments/HomeFragment.kt
  app/src/main/java/io/treehouses/remote/Fragments/NewNetworkFragment.kt
  app/src/main/java/io/treehouses/remote/Fragments/ServicesDetailsFragment.kt
  app/src/main/java/io/treehouses/remote/Fragments/StatusFragment.kt
  app/src/main/java/io/treehouses/remote/Fragments/SystemFragment.kt
  app/src/main/java/io/treehouses/remote/bases/BaseFragment.kt
  app/src/main/java/io/treehouses/remote/callback/HomeInteractListener.java
  app/src/main/java/io/treehouses/remote/callback/HomeInteractListener.kt
Labels: :eye: please review

#874 convert ViewHolderCamera to kotlin
  app/src/main/java/io/treehouses/remote/adapter/ViewHolderCamera.java
  app/src/main/java/io/treehouses/remote/adapter/ViewHolderCamera.kt
Labels: :eye: please review

#884 convert ParseDbService to kotlin
  app/src/main/java/io/treehouses/remote/Network/ParseDbService.java
  app/src/main/java/io/treehouses/remote/Network/ParseDbService.kt
  app/src/main/java/io/treehouses/remote/bases/BaseHomeFragment.kt
Labels: :eye: please review

#876 convert NetworkProfile to kotlin
  app/src/main/java/io/treehouses/remote/pojo/NetworkProfile.java
  app/src/main/java/io/treehouses/remote/pojo/NetworkProfile.kt
Labels: :eye: please review

#875 convert BaseServicesFragment to kotlin
  app/src/main/java/io/treehouses/remote/bases/BaseServicesFragment.java
  app/src/main/java/io/treehouses/remote/bases/BaseServicesFragment.kt
Labels: :eye: please review

#872 terminal: hide anime in help (fixes #865)
  app/src/main/java/io/treehouses/remote/Fragments/DialogFragments/HelpDialog.kt
Labels: :eye: please review

#877 convert SaveUtils to kotlin and refactor
  app/src/main/java/io/treehouses/remote/Fragments/DialogFragments/AddCommandDialogFragment.kt
  app/src/main/java/io/treehouses/remote/Fragments/DialogFragments/BottomSheetDialogs/BridgeBottomSheet.kt
  app/src/main/java/io/treehouses/remote/Fragments/DialogFragments/BottomSheetDialogs/HotspotBottomSheet.kt
  app/src/main/java/io/treehouses/remote/Fragments/DialogFragments/BottomSheetDialogs/WifiBottomSheet.kt
  app/src/main/java/io/treehouses/remote/Fragments/HomeFragment.kt
  app/src/main/java/io/treehouses/remote/Fragments/SettingsFragment.kt
  app/src/main/java/io/treehouses/remote/Fragments/TerminalFragment.kt
  app/src/main/java/io/treehouses/remote/utils/SaveUtils.java
  app/src/main/java/io/treehouses/remote/utils/SaveUtils.kt
Labels: :eye: please review

#897 terminal: command list reactivated
  app/src/main/java/io/treehouses/remote/utils/SaveUtils.kt
Labels: priority

#916 system: no white text (fixes #911)
  app/src/main/res/layout/configure_ssh_key.xml
  app/src/main/res/layout/configure_tethering.xml
  app/src/main/res/layout/configure_wificountry.xml
  app/src/main/res/layout/open_vnc.xml
Labels: :eye: please review, bug, dogi, priority

#879 services: add memory percentage (fixes #706)
  app/src/main/java/io/treehouses/remote/Fragments/ServicesTabFragment.java
  app/src/main/res/layout/activity_services_tab_fragment.xml
Labels: :eye: please review, dogi

#930 tunnel: add tor dialog no white text (fixes #922)
  app/src/main/res/layout/dialog_tor_ports.xml
Labels: :eye: please review, bug, priority

#909 convert TunnelSSHFragment to kotlin
  app/src/main/java/io/treehouses/remote/Fragments/TunnelSSHFragment.java
  app/src/main/java/io/treehouses/remote/Fragments/TunnelSSHFragment.kt
Labels: :eye: please review

#907 convert RPIListAdapter to kotlin
  app/src/main/java/io/treehouses/remote/adapter/RPIListAdapter.java
  app/src/main/java/io/treehouses/remote/adapter/RPIListAdapter.kt
Labels: :eye: please review

#912 convert TorTabFragment to kotlin
  app/src/main/java/io/treehouses/remote/Fragments/TorTabFragment.java
  app/src/main/java/io/treehouses/remote/Fragments/TorTabFragment.kt
  app/src/main/java/io/treehouses/remote/bases/BaseFragment.kt
Labels: :eye: please review

#870 status: submit feedback (fixes #847)
  app/src/main/java/io/treehouses/remote/Fragments/AboutFragment.kt
  app/src/main/java/io/treehouses/remote/Fragments/DialogFragments/FeedbackDialog.kt
  app/src/main/java/io/treehouses/remote/InitialActivity.kt
  app/src/main/java/io/treehouses/remote/Network/ParseDbService.kt
  app/src/main/res/layout/dialog_feedback.xml
  app/src/main/res/layout/fragment_about.xml
  app/src/main/res/menu/initial.xml
  app/src/main/res/values-night/strings.xml
  app/src/main/res/values/strings.xml
Labels: :eye: please review, dogi

#925 convert ServicesTabFragment to kotlin
  app/src/main/java/io/treehouses/remote/Fragments/ServicesTabFragment.java
  app/src/main/java/io/treehouses/remote/Fragments/ServicesTabFragment.kt
Labels: dogi

#943 services: oops (fixes #942)
  app/src/main/java/io/treehouses/remote/Fragments/ServicesFragment.kt
  app/src/main/java/io/treehouses/remote/Fragments/ServicesTabFragment.kt
Labels: :eye: please review, bug, priority

#921 convert ViewHolderWifiCountry to kotlin
  app/src/main/java/io/treehouses/remote/adapter/ViewHolderWifiCountry.java
  app/src/main/java/io/treehouses/remote/adapter/ViewHolderWifiCountry.kt
Labels: dogi

#947 system: wificountry oops (fixes #948)
  app/src/main/java/io/treehouses/remote/adapter/NetworkListAdapter.kt
Labels: :eye: please review, bug, priority

#919 convert ViewHolderSSHKey to kotlin
  app/src/main/java/io/treehouses/remote/adapter/ViewHolderSSHKey.java
  app/src/main/java/io/treehouses/remote/adapter/ViewHolderSSHKey.kt
Labels: dogi

#951 system: oops (fixes #952)
  app/src/main/java/io/treehouses/remote/adapter/NetworkListAdapter.kt
Labels: bug, priority

#937 fixes networkmode text colour
  app/src/main/res/layout/new_network.xml
Labels: dogi

#940 services: update cli handling (fixes #900)
  app/src/main/java/io/treehouses/remote/utils/CommandManager.kt
Labels: :eye: please review, priority

#903 settings: clean switch between normal and dark mode (fixes #902)
  app/src/main/java/io/treehouses/remote/Fragments/ServicesTabFragment.kt
Labels: :eye: please review, bug, dogi

#953 system: oops (fixes #954)
  app/src/main/java/io/treehouses/remote/adapter/NetworkListAdapter.kt
Labels: :eye: please review, bug

#871 home: get started button (fixes #535)
  app/src/main/java/io/treehouses/remote/Fragments/HomeFragment.kt
  app/src/main/java/io/treehouses/remote/InitialActivity.kt
Labels: :eye: please review

#905 convert ChPasswordDialogFragment to kotlin
  app/src/main/java/io/treehouses/remote/Fragments/DialogFragments/ChPasswordDialogFragment.java
  app/src/main/java/io/treehouses/remote/Fragments/DialogFragments/ChPasswordDialogFragment.kt
  app/src/main/res/layout/chpass_dialog.xml
Labels: :eye: please review

#881 refactor or codeclimate is happy
  app/src/main/java/io/treehouses/remote/Fragments/DialogFragments/BottomSheetDialogs/HotspotBottomSheet.kt
  app/src/main/java/io/treehouses/remote/Fragments/HomeFragment.kt
  app/src/main/java/io/treehouses/remote/bases/BaseHomeFragment.kt
  app/src/main/java/io/treehouses/remote/utils/CommandManager.kt
Labels: :eye: please review, priority, refactor

#950 options: dark mode
  app/src/main/res/values-night/styles.xml
  app/src/main/res/values/styles.xml
Labels: dogi

#939 services: tutorial (fixes #931)
  app/src/main/java/io/treehouses/remote/Tutorials.kt
Labels: :eye: please review

#945 status: tutorial (fixes #935)
  app/src/main/java/io/treehouses/remote/Tutorials.kt
Labels: :eye: please review

#981 system: white button text color (fixes #979)
  app/src/main/res/layout/configure_ssh_key.xml
  app/src/main/res/layout/layout_btn_configuration.xml
Labels: dogi, enhancement

#970 system: blocker added (fixes #971)
  app/src/main/java/io/treehouses/remote/adapter/NetworkListAdapter.kt
  app/src/main/java/io/treehouses/remote/adapter/ViewHolderBlocker.kt
  app/src/main/java/io/treehouses/remote/pojo/NetworkListItem.java
  app/src/main/res/layout/configure_blocker.xml
Labels: :eye: please review

#987 about: rounded buttons
  app/src/main/res/drawable/ic_about_btn.xml
  app/src/main/res/drawable/ic_give_feedback.xml
  app/src/main/res/layout/fragment_about.xml
Labels: enhancement

#974 about: refactor (fixes #973)
  app/src/main/java/io/treehouses/remote/Fragments/AboutFragment.kt
Labels: :eye: please review, refactor

#985 tunnel: tor tab in dark mode
  app/src/main/java/io/treehouses/remote/Fragments/TorTabFragment.kt
  app/src/main/res/layout/activity_ssh_tunnel_fragment.xml
  app/src/main/res/layout/activity_tor_fragment.xml
  app/src/main/res/layout/dialog_tor_ports.xml
  app/src/main/res/values-night/color.xml
  app/src/main/res/values/color.xml
Labels: :eye: please review, enhancement

#975 status: temperature added (fixes #976)
  app/src/main/java/io/treehouses/remote/Fragments/StatusFragment.kt
  app/src/main/res/layout/activity_status_fragment.xml
Labels: :eye: please review, enhancement

#968 initial tutorial
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/treehouses/remote/Fragments/HomeFragment.kt
  app/src/main/java/io/treehouses/remote/IntroActivity.kt
  app/src/main/java/io/treehouses/remote/SplashScreenActivity.kt
  app/src/main/java/io/treehouses/remote/Tutorials.kt
  app/src/main/java/io/treehouses/remote/bases/BaseHomeFragment.kt
  app/src/main/java/io/treehouses/remote/callback/IntroPagerListener.kt
  app/src/main/java/io/treehouses/remote/utils/SaveUtils.kt
  app/src/main/res/drawable/ic_bluetooth_icon.xml
  app/src/main/res/drawable/ic_download_icon.xml
  app/src/main/res/drawable/intro_tab_indicator.xml
  app/src/main/res/drawable/intro_tab_indicator_default.xml
  app/src/main/res/drawable/intro_tab_indicator_selected.xml
  app/src/main/res/drawable/rectangle_drawable_white.xml
  app/src/main/res/layout/activity_intro.xml
  app/src/main/res/layout/intro_screen_bluetooth.xml
  app/src/main/res/layout/intro_screen_download.xml
  app/src/main/res/layout/intro_screen_welcome.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: :eye: please review, priority

#918 convert TunnelPageAdapter to kotlin
  app/src/main/java/io/treehouses/remote/adapter/TunnelPageAdapter.java
  app/src/main/java/io/treehouses/remote/adapter/TunnelPageAdapter.kt
Labels: :eye: please review

#878 convert ServicesData to kotlin
  app/src/main/java/io/treehouses/remote/pojo/ServicesData.java
  app/src/main/java/io/treehouses/remote/pojo/ServicesData.kt
Labels: :eye: please review

#964 convert SSHTunnelFragment to kotlin
  app/src/main/java/io/treehouses/remote/Fragments/SSHTunnelFragment.java
  app/src/main/java/io/treehouses/remote/Fragments/SSHTunnelFragment.kt
Labels: :eye: please review

#963 convert RPIDialogFragment to kotlin
  app/src/main/java/io/treehouses/remote/Fragments/DialogFragments/RPIDialogFragment.java
  app/src/main/java/io/treehouses/remote/Fragments/DialogFragments/RPIDialogFragment.kt
  app/src/main/java/io/treehouses/remote/Fragments/HomeFragment.kt
Labels: :eye: please review

#965 convert GPSService to kotlin and Refactor
  app/src/main/java/io/treehouses/remote/utils/GPSService.java
  app/src/main/java/io/treehouses/remote/utils/GPSService.kt
Labels: :eye: please review, priority

#993 update .gitlab-ci.yml (fixes #992)
  .gitlab-ci.yml
Labels: :eye: please review
